### ISSUE TITLE
Provide a proper data science template

### ISSUE THREAD

**Issue by FlorianWilhelm** [pyscaffold/pyscaffold#192]
Whenever I use PyScaffold in my Data Science projects I feel like I am doing the same things right after calling `putup` like creating a `data` folder and so on. Thus I think the time is ripe for some cool data science project extension just like the [cookiecutter-data-science project](https://github.com/drivendata/cookiecutter-data-science). I have already created an [issue](https://github.com/drivendata/cookiecutter-data-science/issues/126) there and it seems they are cool with us copying large parts of their structure.

**Comment by quazzuk** [comment]
+1

**Comment by hershelm** [comment]
+1

**Comment by jbusecke** [comment]
Hi I just discovered pyscaffold, and would like to use it to set up project repositories for my day to day analysis of scientific data (ocean circulation models, satellite data and observations).
This differs slightly from the cookiecutter template mentioned, but that is mostly in the folder structure for now.
I would love to contribute an extension but would probably need some pointers.

I prefer to implement my travis-CI and environments with conda, is that supported yet?

**Comment by FlorianWilhelm** [comment]
@jbusecke Welcome! If you want to develop your own extension it's best to start reading the [extension docs](https://pyscaffold.org/en/latest/extensions.html). Then take a look into the [PyScaffold organisation](https://github.com/pyscaffold) where you will find several example extensions like [markdown](https://github.com/pyscaffold/pyscaffoldext-markdown) and [custom-extension](https://github.com/pyscaffold/pyscaffoldext-custom-extension). Use this custom-extension to help you set up your own extensions using `putup --custom-extension your_extension`. 

Regarding your second question, PyScaffold is using conda too for its tests. And the current `travis_install.sh` template even uses miniconda to set everything up. Does this answer your question?

**Comment by jbusecke** [comment]
Yes thanks a lot for the reponse. Ill look into these.

**Comment by KiemNguyen** [comment]
@FlorianWilhelm This is exactly what I'm trying to do for our Data Science team. I have been "hacking" the extension and I would love to contribute.

**Comment by FlorianWilhelm** [comment]
@KiemNguyen cool to here from you. I am always happy about new contributors? Have you looked already into https://github.com/pyscaffold/pyscaffoldext-custom-extension ? I started some work on Master but wasn't able to completely finish it before my vacation. Still it's a good starting point for how a custom extension should look like. Let me know if you need more info. 

We could start by discussing how a data science template should look like.

**Comment by FlorianWilhelm** [comment]
@KiemNguyen, @jbusecke, @hershelm, and @quazzuk: I created a very first version of a data science extensions under [pyscaffoldext-dsproject](https://github.com/pyscaffold/pyscaffoldext-dsproject) which can already be installed via pypi. It's rather an alpha version but I am looking for feedback. Please post your thoughts in the issue tracker of the extension itself. Thanks!

**Comment by jbusecke** [comment]
FWIW I actually decided to stick with cookiecutter and create a [preset](https://github.com/jbusecke/cookiecutter-science-project) that is a bit more focused on data analysis of existing output (motivated by my earth science work).

**Comment by FlorianWilhelm** [comment]
@jbusecke Thanks for letting me know. Still, if you have any feedback on [pyscaffoldext-dsproject](https://github.com/pyscaffold/pyscaffoldext-dsproject), I would value your feedback.

**Comment by hershelm** [comment]
Hey Florian, thanks for creating this! I just gave it a glance, and it looks exciting. I will start using it for a project at my company and let you know how it goes.

**Comment by hershelm** [comment]
Also, a quick question, do you know of an example of a somewhat completed or mature (i.e., production-ready) data science project using pyscaffold? That would better guide our ability to use this extension to build production-ready code (just watched your talk on scaling data science to productoin, and found it quite useful). 

Any guidance is always appreciated, and I can clarify or take this request to a different forum if that's more helpful.

**Comment by FlorianWilhelm** [comment]
@hershelm Thanks for your feedback, glad that you like it! Let me know how it works for you, I am interested in more feedback. 

Regarding your question. Data scientists are actually not known for clean coding and making production-ready code which is one of the reasons I started with PyScaffold and the Data Science Template for it. With respect to the source code, it's best to have a proper package, do versioning, adhere to clean code principles, have quality standards, and CI set up properly. Deployment then depends on your use-case, maybe you dockerize everything and have a REST API or your package just provides a console script and runs a batch job. Since the data science extension is quite young, I know of no repository showing production-ready code that uses it and hardly any company will just show you their production code. But if you find something let me know.

BTW, have you also read my blog posts [Working efficiently with Jupyter Lab](https://florianwilhelm.info/2018/11/working_efficiently_with_jupyter_lab/) and [Data Science in Production](https://florianwilhelm.info/2018/01/ds_in_prod_packaging_ci/) yet?
