### ISSUE TITLE
setup.cfg long-description-content-type prevents release on pypi

### ISSUE THREAD

**Issue by sea212** [pyscaffold/pyscaffold#229]
I setup a project using pyscaffold 3.1. Setup.cfg contained the following line:
``long-description-content-type = text/reStructuredText``
I could not push my project on pypi because it expected:
``long-description-content-type = text/x-rst``

**Comment by FlorianWilhelm** [comment]
Thanks, might it be that you rather use the current master instead of a released version? Can you provide a PR?

**Comment by sea212** [comment]
In version 3.1 there was no "long-description-content-type" key specified in the setup.cfg.template:
https://github.com/pyscaffold/pyscaffold/blob/v3.1/src/pyscaffold/templates/setup_cfg.template

In the current master branch though, the line is specified correctly:
https://github.com/pyscaffold/pyscaffold/blob/master/src/pyscaffold/templates/setup_cfg.template#L12

Therefore I assume that this bug does not exist in the current master branch anymore.
After looking through the issue I see that this issue was already fixed: https://github.com/pyscaffold/pyscaffold/issues/216

**Comment by FlorianWilhelm** [comment]
Ok, cool, thanks. That means we can use this.

**Comment by sea212** [comment]
Note that the key "long_description_content_type" is written with underscores in the official setuptools package: https://github.com/pypa/setuptools/blob/master/setup.py#L99

When I pushed my package on pypi today, it accepted the variant with the "-" instead of "_".

**Comment by FlorianWilhelm** [comment]
Thanks for letting me know. I think dashes and underscores can be used interchangeable almost everywhere in setuptools.
