### ISSUE TITLE
How to setup a platform dependency in pyscaffold?

### ISSUE THREAD

**Issue by TTimo** [pyscaffold/pyscaffold#230]
Hello,

I need to add pywin32 as a dependency for Windows platforms to my pyscaffold based python project. I have found some information on how to do it for setup.py projects, but not something that uses setup.cfg, seems like the semicolon separator would prevent a syntax such as `pywin32>=223;platform_system==Windows`

Help?

**Comment by FlorianWilhelm** [comment]
Hi,

you could try out using line breaks to separate dependencies. In this case you got the semicolon left to specify the platform. Check out [this example](https://github.com/psychopy/psychopy/blob/master/setup.cfg).

Cheers,
Florian

**Comment by TTimo** [comment]
Thanks! That worked great .. I didn't expect the one module per line would do it ..
