### ISSUE TITLE
Disable setuptools_scm

### ISSUE THREAD

**Issue by TyberiusPrime** [pyscaffold/pyscaffold#232]
## Describe your use-case
For reasons (which start with setuptools-rust and end with poetry-might-do-what-pip-doesn't),
I need to disable the scm derived version numbers for a project and define my version without executing code (ie. in setup.cfg).

## Describe the solution you would like to see for your use-case
setuptools_scm doc says there's a use_scm_version argument for setup(), but that does not work within pyscaffold.
Is there a work around?

(I suppose it would be cool if pyscaffold disabled setuptools_scm iff there was a version in setup.cfg)

**Comment by TyberiusPrime** [comment]
Ok, I have an ugly, ugly, ugly work around for the current relased pyscaffold
using monkey patching:

a) add pyscaffold to pyproject.toml build-system, so we can import pyscaffold in setup.py
b) setup.py
```python
if __name__ == "__main__":
    import pyscaffold.contrib.setuptools_scm.integration

    def restore_setup_cfg_version(dist, keyboard, value):
        import configparser

        c = configparser.ConfigParser()
        c.read("setup.cfg")
        dist.metadata.version = c["metadata"]["version"]

    pyscaffold.contrib.setuptools_scm.integration.version_keyword = (
        restore_setup_cfg_version
    )

    setup(
 ```

**Comment by FlorianWilhelm** [comment]
Have you tried `setup(use_pyscaffold=False)` in `setup.py`? You will, of course, lose some other features as well but it might do what you want.

**Comment by TyberiusPrime** [comment]
Am I correct in my reading of the code that all that I'm going to lose is the doc/doctest/sphinx/test commands for setup.py?

**Comment by FlorianWilhelm** [comment]
Exactly

**Comment by TyberiusPrime** [comment]
I belive I can live with that :).
