### ISSUE TITLE
[setuptools_scm] Error setting up the development environment

### ISSUE THREAD

**Issue by n-batalha** [pyscaffold/pyscaffold#233]
## Error setting up the development environment

Following the instructions [here](https://pyscaffold.org/en/latest/dependencies.html#development-environment) for pipenv but adding `--pyproject`.
```bash
putup scaffold_example -d "Dummy description" -l mit --pyproject
cd scaffold_example
pipenv --python 3.7
pipenv run python setup.py develop
pipenv install -e .
```

I get [this traceback](https://github.com/pyscaffold/pyscaffold/files/3242727/stack-trace-1.log).

---

### Optional info:

* If either omitting `--pyproject` or removing `setuptools_scm` that's on the generated `pyproject.toml`, the issue doesn't occur. 
  * without `setuptools_scm` on `pyproject` I still seem to get versions from scm (e.g. `pipenv run python setup.py --version`) but I'm not familiar with this *_scm project.
* This was an attempt to reproduce the issue from scratch that's on a very similar project, but not clear why the issue, also on setuptools_scm, has a  [different traceback](https://github.com/pyscaffold/pyscaffold/files/3242735/stack-trace-2.log).

## Versions and main components

* PyScaffold Version: 3.1
* Python Version: 3.7
* Operating system: Fedora 29
* How did you install PyScaffold: pip

**Comment by FlorianWilhelm** [comment]
Thanks for posting this issue. The `pyproject` plugin is a bit outdated and I definitely need to update it soon.

**Comment by FlorianWilhelm** [comment]
In version 0.2 of the pyproject extension, I removed setuptools_scm from `pyproject.toml`. Thanks for reporting this issue.
