### ISSUE TITLE
On the road to PyScaffold 4.0

### ISSUE THREAD

**Issue by FlorianWilhelm** [pyscaffold/pyscaffold#235]
## General discussion

This issue is a stub for everything that needs to be done and general discussion for the preparation of a PyScaffold 4.0 release which will include breaking changes.

**Comment by FlorianWilhelm** [comment]
@abravalheri , let's discuss here what needs to be done to get the `v4.0.x` branch building again as well as the new extensions for django and cookiecutter. I think it makes sense to have `setup_requires` in a way that extensions either work with PyScaffold 3.2 or 4.0 to avoid version conflicts when we include breaking changes. Do you agree?

To fix the unit tests I already released an alpha version of PyScaffold 4.0 and I think I also need to do this for all the current extensions we have like dsproject, pyproject etc. I would do so by just choosing a higher version number and also releasing an alpha or beta version with corresponding `setup_requires` for PyScaffold 4.0. This would avoid the problems we are having right now with the PyScaffold 4.0 unit tests. Do you agree?

**Comment by abravalheri** [comment]
Hi @FlorianWilhelm, great thinking!

Do you mean putting a cap on setup_requires (like you are doing nowadays for 3.2)? Something like: `setup_requires = pyscaffold>=4.0a0,<4.1a0`. I think this should be fine... Should we do `<4.1a0` or `<5.0a0`? Since are following semantic versioning, all the extensions that work on 4.1 will automatically work until 5.0. If we start with the cap in 5.0, when we release the next minor versions of PyScaffold, we can keep bumping the minimal. This way, we don't need to keep going to the extensions and update them.

Regarding the roadmap, I think we can address #215 and #219 relatively easily, because we have already a plan for that.

#218 is a little more tedious, since we have to go through all the extensions making sure the `__init__.py` files are empty and creating new releases.

#138 would be great to have. I have a proposal on how to rewrite `--update` as a built-in extension, but since what I envision it is back compatible, we can just go ahead with the initial plan.

#191 is more complicated though... In order to be able to have an interactive front-end (or something like an UI), we have to dissociate the concept of `parameters` and the internal implementation with `argparser`, and this might break the documented APIs. I will elaborate more in the open issue.

**Comment by abravalheri** [comment]
As a new improvement, #236 would be excellent to have (however, since it is non-breaking improvement, it can be shipped in a minor version bump) 😄

**Comment by FlorianWilhelm** [comment]
@abravalheri you are right about the cap in `setup_requires`, i.e. `setup_requires = pyscaffold>=4.0a0,<4.1a0`. Maybe from version 4.0 on we should switch to `<5.0a0` by default and just increase the major version more often whenever we break the extension API (which we should only do for good reasons.). This would also mean that we need to change `get_install_requires_version` in the `custom_extension` extension to increase the major version. Do you think we should also have a pyscaffold 4.0 branch for every extension? Just to make sure we don't mix up things? I really think it's gonna take us a while until we have a proper version 4.0 and in the meantime we might need to have fixes in the extensions for PyScaffold 3.2.

**Comment by abravalheri** [comment]
Hi @FlorianWilhelm, I have included 2 proposals as PR's recently that involve changing the API #294 and #295 (the first one is not exactly backwards compatible, although it can be made *sort-of* compatible), and 2 more as issues #296 and #297.

If you agree I can try to work on them (although it would be nice to have the help of @smartsammler for the gitlab-ci stuff).

I am postponing the easy changes (e.g. #266) and the `pyproject.toml` bomb when I feel that most of the API changes are done.

#236 is basically functional on the v4.0.x branch (although incomplete: there is no ``--config`` and ``--save-config`` flag). But implementing it after 4.0 is launched should be incremental and not break any API.

**Comment by FlorianWilhelm** [comment]
Hi @abravalheri, sounds good to me. I am also fine with introducing breaking changes for version 4, so #294 is fine. Seems like a major overhaul of PyScaffold and I am looking forward to it. Sorry, that I am of not of much help but I got quite a lot on my plate right now. I just want to quote Antoine de Saint-Exupery who said 

> Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away.

This doesn't mean *primitive obsession* as you can have elegant data structures to have an elegant solution. One just should always be careful to not overcomplicate things and add every feature that someone asked for.

That being said, I totally trust you and am excited for what's to come in version 4.0 :-)

**Comment by abravalheri** [comment]
Thanks @FlorianWilhelm! So I will proceed and before the release we can organise a review/discussion.

Regarding the changes in API, to be fair I have the impression it actually simplifies stuff... I we skip the additions in terms of documentation (which I went a bit overboard), I have the impression the implementation shrank a bit (I deleted 2 huge complicated functions in the updates module to add 3 small and simple ones. After that change was made, adding the feature requested was a matter of 4 lines of code that actually do something (which to be sincere doesn't even need to be there... but I found it to be a nice re-usable addition)

**Comment by abravalheri** [comment]
I think we are getting closer to v4, finally! Most of the issues assigned in the road map are closed, indeed there are just a few new ones that I opened while implementing and thinking about the code.

It seems to me that #309 is worthy handling before v4, so PyScaffold is slightly more future-proof, and there are my 2 proposals about tox and gitlab pending for consideration.
I might go forward with the tox proposal, since there will be a escape hatch (`--no-tox`) and we are just flipping the logic between opt-in to opt-out, and I feel like this would encourage good practices.

**Comment by FlorianWilhelm** [comment]
Hi @abravalheri, 

I think using tox really is a good practice and it's better to add it as default, therefore I find your `--no-tox` idea good. Since Gitlab-CI gets more and more important I think having it directly as an internal extension makes sense as you suggested. 

Also, 4.0 is a great opportunity to get rid of old stuff like pkg-resources #309, which means I totally agree with you that it might make sense to handle it before. In general, sticking with semantic versioning and only breaking things in major versions like 4.0 would be my suggestion but please decide as you see fit. 

It's also great to see that you simplify PyScaffold. I hope it will make maintainability easier in the future and maybe we find even more contributors by keeping the entrance hurdle low.

Thank you. Is there anything else I forgot?

**Comment by abravalheri** [comment]
That was pretty much it @FlorianWilhelm thanks for the comments, I will keep the issues updated (probably I am going to slow down a bit the next weeks, but I hope we can have v4 in a few month).

I am about to release a beta for 3.3, so that would be also nice :)

**Comment by FlorianWilhelm** [comment]
Should first the final version 3.3 be released first, then maybe 2-3 weeks waiting and seeing if anything pops up while at the same time testing some version 4.0 betas, followed by the 4.0 release?

**Comment by abravalheri** [comment]
I agree with this approach, it makes ton of sense. I published a beta a few days ago, but not so sure if we will have feedback on that one... I suppose the only thing left to add is the docs about `include_package_data` as we are discussing in #278?

I will try to release a v4 beta this week, so we can also start fixing the extensions regarding the breaking changes in API.

**Comment by abravalheri** [comment]
Also, after adding the `include_package_data` stuff to the docs, I suppose it makes sense to make v4.0.x the master branch and create a v3.3.x

**Comment by FlorianWilhelm** [comment]
Is an interactive feature as described in #191 something that would lead to another breaking change or something that could be included in version 4.1?

**Comment by abravalheri** [comment]
That is a tricky one :P 

The way I understand this problem (and how I would give it a go) is:

> How can we implement the interactive feature without having to repeat everything specified for the CLI (argparse) and in a transparent way so new extensions are automatically added to the interactive prompt?

The best, but at the same time impossible way of doing that would be inspecting the `ArgumentParser` object dynamically and preparing the question/options presented to the user based on the `help` text for the CLI/default values/`argparse.Actions`. Unfortunately all the ways of doing that involve accessing private vars in the object (they are prefixed with an `_`). So the solutions we have are equally painful:

1. Replace argparse and change the APIs in a very much non backward compatible way
2. Still use argparse, but not directly, instead just collect the options and arguments in a nice data structure that can be used later to build both the argparser and the interactive stuff. Also a breaking change.
3. Inspect the private vars of argparse anyway, they have being there for ages and don't seem that will change very soon... This do not require breaking changes.
4. Do double-bookkeeping and have yet another API for the interactive stuff. So I guess we can say it is a backward compatible change? But not a nice way of doing that.
5. Put a proxy object on top of argparse that record the parameters in a special data structure and fallback to 2. In my opinion keeping the proxy in sync with the argparse API would be slightly less problematic then option 3 (the probability Python core members change it is slightly smaller), although more elegant.

I guess the only way of knowing is by starting the implementation.

**Comment by FlorianWilhelm** [comment]
Okay, do you think there is any real good reason to stay with `argparse` or use the 4.0 release to switch to a library that supports all this directly? Maybe there is one, I'll do a little research in the next days.

**Comment by FlorianWilhelm** [comment]
@abravalheri, okay, having checked your former comments and having looked a bit at `click` again, I see why in the case of PyScaffold it makes sense to stay with `argparse` to have a cleaner separation between parsing the args and using the results. I wish there would even be the possibility to even separate the actual parsing from the validation as this could be also used later if someone would use PyScaffold as a library. 

Have you seen https://pypi.org/project/argparse-prompt/ yet? I will check it out, maybe this is something we could use or apply a similar technique for the interactive mode in PyScaffold.

**Comment by abravalheri** [comment]
Hi @FlorianWilhelm, thanks for the link! I just had a look the guys working in the argparse-prompt where really clever to abuse the `type` machinery to do the interactive magic 😛 

In some way, it works more or less like the option 5 I was mentioning before... I wonder if it is safe to assume that the only method of argparse that is relevant for the "interativeness" is `add_argument`...

My quick and dirty idea (in 3) was just to inspect `ArgumentParser._actions` and use something like [inquirer](https://github.com/magmax/python-inquirer) to sintetize the questions from them... Yeah, it is bad, it is private ... but `argparse` objects do not offer other way of introspection (unless you write a layer on top)...

**Comment by FlorianWilhelm** [comment]
Yeah, I also find it pretty neat what they do. Since I am on vacation the
next two weeks, I'll have some time to play around a bit and would push it
on some extra branch. Maybe we can then discuss if it makes sense.
Since they use GPL3 and it's really not much code I would rather use a
similar but independent approach and but it directly into Pyscaffold. Fine
by you?

**Comment by abravalheri** [comment]
Perfect, @FlorianWilhelm, I will leave that to you then and proceed with porting the extensions to v4!
Let me know if you need help with something.

**Comment by abravalheri** [comment]
🥳  [v4.0a2](https://pypi.org/project/PyScaffold/4.0a2/) is now on PyPI (with hopefully most of the breaking changes in terms of API).

**Comment by FlorianWilhelm** [comment]
@abravalheri I did some tests with `argparse-prompt` and although their trick is neat is doesn't work for many actions of `argparse`. For instance, it fails if you use `action='store_true'` as in this case there is no `type` argument allowed. Python 3.8 supports custom Actions and a similar trick as with `type` would be possible but we want to support Python >=3.6 and it doesn't feel clean anyway. 

I will now check out your solution 3 as it seems the best solution in that case. Reading a private/protected variable is fine I guess if one first inherits from the `ArgumentParser`.

**Comment by abravalheri** [comment]
I believe I ported all the extensions that needed to be ported to use the most updated version of PyScaffold's API. I also tagged  a bunch of them, but unfortunately I don't have access to all the projects in PyPI so I could not release alphas/betas for all of them. The situation is:

- [x] PyScaffold `v4.0a3`, development in the **v4.0.x** branch
- [ ] pyscaffoldext-django `v0.1b3`, development in the **master** branch
- [ ] pyscaffoldext-cookiecutter `v0.1b3`, development in the **master** branch
- [x] pyscaffoldext-markdown `v0.4a3`, development in the **pyscaffold-v4** branch
- [ ] pyscaffoldext-custom-extension `v0.6a2`, development in the **pyscaffold-v4** branch
- [ ] pyscaffoldext-dsproject `v0.5a1`, development in the **pyscaffold-v4** branch

(with the checkbox meaning uploaded to PyPI)

**Comment by FlorianWilhelm** [comment]
Hi Anderson,

thanks so much for all your work. I'll change the permissions in the
evening as I am right now in the car on the way to a larger hike in
Austria.

When is was playing around a bit I managed to install Pyscaffold 4.0 with
the old extensions which lead to an error which was easily fixed by
uninstalling the extensions. That led me to the question if it would be
possible to have a somewhat nicer error message during the loading of an
extension that tells a user directly that there was a problem loading
extension XY.

Cheers, Florian

**Comment by abravalheri** [comment]
Thanks @FlorianWilhelm and sorry for the delay, I just uploaded the missing alphas/betas.

**Comment by CarliJoy** [comment]
@abravalheri are the API Changes for v4.0 documented somewhere already?
I would be interested in updating my companies internal extension once v4.0 is released.

Thanks for all your work guys, btw :)

**Comment by abravalheri** [comment]
Hi @CarliJoy very good to know you are using PyScaffold :) I hope the experience have been a pleasant one.

I am trying to keep the documentation up to date as I change the code, so we have "hidden" docs for the new version on https://pyscaffold.org/en/v4.0.x/ (I am keeping it hidden because we are still working on the beta and therefore, it's subject to change).

As a quick example, you can check the new template for custom extensions:

https://github.com/pyscaffold/pyscaffoldext-custom-extension/blob/pyscaffold-v4/src/pyscaffoldext/custom_extension/templates/extension.template

I think the most important changes for extension authors are:
- the `helpers` modules is gone... now its functions are distributed in other modules with more "semantic" names (at least in my opinion :P)
- the dict struct representing the project  directory now does not include the project root folder
- `NO_OVERWRITE` and `NO_CREATE` flags were replaced with `pyscaffold.operations` function (roughly speaking `pyscaffold.operations import no_overwrite; NO_OVERWRITE = no_overwrite()`).

(You will find updated examples and descriptions on https://pyscaffold.org/en/v4.0.x/extensions.html)

I hope it helps

**Comment by CarliJoy** [comment]
@abravalheri thanks for your help.
Is there a timeline for the release of the 4.x version?
During Christmas I have some time off (you know lockdown and so one) and I could help out a bit bringing life to the 4.x version.
But I don't see any open issues regarding the 4.x version, so where would be a good place to start?
@FlorianWilhelm maybe you could help out here?
