### ISSUE TITLE
Introduce global config

### ISSUE THREAD

**Issue by abravalheri** [pyscaffold/pyscaffold#236]
Since PyScaffold users probably use `putup` to create new packages in a recurring basis, it would be nice to allow them to "save" their favourite options somewhere.

### Proposal
The `create_project` function could deep merge the arguments coming from the current sources:
1. Global configuration file (or file specified by an `--config PATH` flag)
2. Local `setup.cfg` (or maybe `pyproject.toml` like everyone seems to be doing nowadays?)
3. Given arguments (via cli or direct api call)
(in order)

Additionally a flag `--save-config` could be used in any `putup` invocation to save the given parameters to the global config file (to *bootstrap* the config file creation).

### Global Config File:
Something following what PyScaffold already does with per-project `setup.cfg`, but in a global location:
- *OSX*: `~/Library/Preferences/pyscaffold/default.cfg` (or something like that)
- *Windows*: `C:\Users\<username>\AppData\Local\pyscaffold\pyscaffold\default.cfg`
- *Linux/Others*: `$XDG_CONFIG_HOME/pyscaffold/default.cfg` with fallback to `~/.config/pyscaffold/default.cfg`
(Please check [`appdirs`](https://pypi.org/project/appdirs/) for more info).

**Comment by abravalheri** [comment]
Example of possible config file:

```ini
[metadata]
author = John Doe
author_email = john.joe@gmail.com
license = mit

[PyScaffold]
extensions = 
    django
    tox
    travis
    cookiecutter
    namespace
cookiecutter = /path/to/template
namespace = my_namespace.my_sub_namespace
```

Please notice that if `author` and `author_email` are present in the global config, we don't have to use `git config --get`.

Currently, extension classes have an `args` property that are being serialized as a string. I believe that, if this option is a dictionary, we can create a new subsection. This would allow us to do something like:

```ini
[metadata]
# ...

[Pyscaffold]
# ....

[Pyscaffold:update]
strategy = keep
except =
   setup.py
   tests/conftest.py
```

(Related to #138)

**Comment by FlorianWilhelm** [comment]
I like this feature and it can be quite easily added, right? Even as an extension maybe, that would be great. Then we could see how many people use it and it would be less invasive.

**Comment by abravalheri** [comment]
Global config is now added, the only thing left is to at least add an option to specify using no file (custom file location might be added but not strictly necessary)

**Comment by abravalheri** [comment]
The missing parts are done in #304
