### ISSUE TITLE
Some tests failing on Windows

### ISSUE THREAD

**Issue by abravalheri** [pyscaffold/pyscaffold#244]
After the discussion in #242, it is evident that Windows support is important for PyScaffold.
#243 address this topic by adding automated tests on Windows via Cirrus CI. However, as indicated in one of the [Cirrus CI builds](https://cirrus-ci.com/task/5836154039959552), some tests are still failing on Windows (despite of a huge effort I put into debugging it 😢)

- [test_info.py:19](https://cirrus-ci.com/task/5836154039959552?command=test#L632) error seems to be just silly, and I don't understand why it is happening.
  According to [Python docs](https://docs.python.org/3.5/library/getpass.html), if `USERNAME` is set, we shouldn't be seeing this error... But we are.
  This is not super important since the user is supposed to configure git anyway...
  So I am wondering, should we skip this test on Windows using PyTest marks?

- [test_repo.py:74](https://cirrus-ci.com/task/5836154039959552?command=test#L1299) error is enigmatic...
  I have 0 clues why we don't have access rights to the git repository.
  If we can create the folder, we should be able to remove it...
  But again, it might not be super important... Looks like it is a super specific sequence of actions in the CI env that is causing that...

- [test_install.py:123](https://cirrus-ci.com/task/5836154039959552?command=test#L3980) error is laughable...
  `The filename or extension is too long` is a very poor error message for the fact that Microsoft hardcoded a 260 char limit for file names and never bothered correcting it...
  [It doesn't seem to be easy to solve](https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/), but yet again not super important.
  It is an issue with the test suite, not necessarily PyScaffold itself.

The remaining error messages seem to be related, at first glance, to #238 (problems with virtualenvs - particularly testing `bdist`s seems to be a recurring pain... to the first time we have problems with that test case).

@FlorianWilhelm do you have any thoughts on this matter, or any approach for dealing with the errors on Windows?

**Comment by FlorianWilhelm** [comment]
Hi @abravalheri, thanks a lot for your debugging efforts. Regarding your points:

> test_info.py:19 error seems to be just silly, and I don't understand why it is happening. According to Python docs, if USERNAME is set, we shouldn't be seeing this error... But we are. This is not super important since the user is supposed to configure git anyway... So I am wondering, should we skip this test on Windows using PyTest marks?

This seems to be related that `pwd` is not available on Windows. It says `ModuleNotFoundError: No module named 'pwd'` in the error. This seems to be quite a common problem judging from Google. I would just deactivate this test for Windows and add a comment that says "Module pwd is not available on Windows".

> test_repo.py:74 error is enigmatic... I have 0 clues why we don't have access rights to the git repository. If we can create the folder, we should be able to remove it... But again, it might not be super important... Looks like it is a super specific sequence of actions in the CI env that is causing that...

This seems to be related to [Windows setting the .git subdirectory read-only](https://stackoverflow.com/questions/2656322/shutil-rmtree-fails-on-windows-with-access-is-denied). One could supply a helper function that unsets the read-only flag on Windows systems or we just deactivate this test for Windows.

> test_install.py:123 error is laughable... The filename or extension is too long is a very poor error message for the fact that Microsoft hardcoded a 260 char limit for file names and never bothered correcting it... It doesn't seem to be easy to solve, but yet again not super important. It is an issue with the test suite, not necessarily PyScaffold itself.

This error is really odd and laughable. Here I would definitely propose to just deactivate the test with a proper comment and wait for other people to fix this issue on Windows. Googling shows up tons of projects with the same problem and the only workarounds seem to be setting some registry key or just making sure that the path is shorter. If both workarounds are not easily applicable for us, skipping those tests and waiting for a solution, is the best way to proceed.

**Comment by abravalheri** [comment]
Hi @FlorianWilhelm, thank you for all your comments.
Yes, definitely proper support for Windows with tests integrated in the CI is a very very big challenge... I think I lost some hair since last week.

> This seems to be related that pwd is not available on Windows. It says ModuleNotFoundError: No module named 'pwd' in the error.

The annoying part is that, `pwd` is not really the reason. It is meant to be that way. The module `pwd` is intentionally exclusive to POSIX. According to the docs, as long as `USERNAME` env var is defined in Windows, everything should be fine... BUT Python seems to be ignoring this env var (I have included it in `.cirrus.yml`! Doing remote debugging just with the CI logs doesn't help to understand why 😢 )

I still believe we should skip this test, despite not knowing exactly the origin of the error. `git` is expected to be installed before running PyScaffold, anyway. PyScaffold with the one of the changes I introduced last time, PyScaffold should output a nice error message asking the user to configure it, so everyone is happy. Progressive enhancement: posix users will have the perk of not needing to configuring git, but windows users won't.

I still don't know how to tackle the permissions problem. In my mind, since we are inside the windows container, it is natural to assume we should be running as admin. But this is beyond my knowledge. I have searched for ways to elevate the permissions, forums seem to point out to tools like `runAs`, but my feeling is that it wouldn't work in a full automated environment without pop-ups asking for confirmation.

Finally, I have a clue about the "long file name" issue.
As I have mentioned, this is not the first time we have problems with `bdist`s.
It took me a while to understand, but it seems that, when running `python setup.py bdist` from inside a virtual env, the command will generate a `tar.gz` file, with absolute paths to inside that virtual env. 

The [documentation](https://python.readthedocs.io/en/stable/distutils/builtdist.html?highlight=zip#creating-built-distributions) is a little bit cryptic and mislead to the understanding that paths in the generated archive file will by default relative to the prefix.
However, it seems that what authors really mean with this text is that `setup.py` will **actively prepend the source files' paths with the absolute path to the current python prefix**. And that is a basically a recipe to caos when running setuptools from inside a venv (the generated tar files will not be portable - instead they will contain absolute paths that just make sense in the developer's machine).

The solution seems to be using `python setup.py bdist_dumb --relative` instead (*I still have to test that*). This way we don't have [crazy nested absolute paths on windows](https://cirrus-ci.com/task/5408824645648384?command=test#L1143), and therefore we don't break the size limit. Maybe it is worth to include this behaviour in the documentation. (Who would say Windows is helping to find some hidden bugs???)

By the way, I am using #239 as a sandbox for debugging these things. Although the PR in the end might not be merged, the only way of having this  flexibility for debugging is using custom code and ditching pytest-virtualenv. Specially when everything have to be done in a slow cycle relying on the logs of the CI environment... (and that is my excuse for an enormous amount of consecutive commits changing the same thing, force pushes and commit messages starting with `"Attempt to ..."` 😝 )

**Comment by abravalheri** [comment]
We are also having ` [SSL: CERTIFICATE_VERIFY_FAILED]` errors that prevents `python setup.py` invocations from inside the system/installation tests to download PyScaffold from PyPI during the build, as instructed by the `setup_requires` key in `setup.cfg`. ([CI logs](https://cirrus-ci.com/task/5408824645648384?command=test#L2307))

This is related to the recent changes in the URLs used by the PyPI (after the warehouse update), and a quick search indicates this problem is very common when running pip as well, and the most recommend workaround is to add `--trusted-host` flags to pip, `PIP_TRUSTED_HOST` env vars, or even an entire `pip.conf/pip.ini` file. However, this workaround does not work for setuptools, because pip is not even involved during build.

Instead the most informative reference I could find is pypa/pip#4156.

**Comment by FlorianWilhelm** [comment]
@abravalheri, this seems to be quite serious! Do the `[SSL: CERTIFICATE_VERIFY_FAILED]` errors also affect PyScaffold 3.2? Is this only Windows related or also Linux/Mac? 

Regarding the other Windows errors, too be pragmatic I guess we could just skip them for Windows but should definitely note why the test would fail and even reference the issue somewhere so that we can later fix it when some upstream projects fixed their problems. 

Just again regarding the Windows access problem. Windows has a kind of marker that makes files read-only, also for admins. This is why one needs to use `chmod` to unset this `read-only` marker, e.g.
```
if not os.access(path, os.W_OK):
     # Is the error an access error ?
     os.chmod(path, stat.S_IWUSR)
```

**Comment by abravalheri** [comment]
Hi @FlorianWilhelm, I forgot to mention that yesterday I addressed some of those bugs in my sandbox #239.

- For the non-sense errors, I am still running the tests, but marking them as `xfail` with the help of pytest. I have added a message indicating the reason why it is failing, but haven't managed to display the trace and logs, without making pytest consider them failures.

- The `bdist` problem, in theory, is solved by `python setup.py bdist_dumb --relative` (indeed it works on POSIX systems). However there is a [very old bug open](https://bugs.python.org/issue993766) that prevents `bdist_dumb --relative` to work on windows. So I have also marked these tests with an `xfail`

- Regarding `[SSL: CERTIFICATE_VERIFY_FAILED]`, I was concerned that we would need to appeal to something like `pyproject.toml` (and that would be difficult because I don't think setuptools fully supports it, specially to the point to include `trusted-host` params there). Fortunately, the errors were magically solved by installing/upgrading the package `certifi` as briefly mentioned in pypa/pip#4156. Of course, in order to allow the nested pip to install it at first place, I added a `PIP_TRUSTED_HOST` env var to windows in `.cirrus.yml`.
  I don't know if this error is affecting PyScaffold 3.2, my guess is that  probably; depending on how Python was installed... It seems that a frozen set of certificates ships with Python, and if they were created before the migration of PyPI to the new addresses, then it would be problematic. This situation is even more complicated when building the package inside a venv, because venvs are bootstraped with the bundled version of pip/setuptools/certicates and ignore any further updates that the user might have done.
  It is not trivial to find the versions of the certificates from inside python to display a warning to the users requiring to update, so I think we could include this workaround on PyScaffold's FAQ...

Please feel free to review the PR and even if not merging it, steal some code from there.

I still have to try the permissions workaround you presented.

**Comment by abravalheri** [comment]
> ```
> if not os.access(path, os.W_OK):
>      # Is the error an access error ?
>      os.chmod(path, stat.S_IWUSR)
> ```
Hi @FlorianWilhelm, since Python do not offer a recursive `chmod` operation, I am a little bit attempted to just leave the Cirrus CI deal with the created temporary folders... They are all created using `tmpdir` so, the SO should be able to clean everything when needed... specially considering the ephemeral nature of the CI environment (containers and VMs...)

**Comment by FlorianWilhelm** [comment]
@abravalheri, agreed. You are right, it's actually a problem in the virtual environment or tox which seems to do the unlinking. Should we create an corresponding issue there? It seems to be a bug in `_rmtree_unsafe` within `..\..\..\..\cirrus-ci-build\.tox\all\lib\shutil.py
:395:`

**Comment by FlorianWilhelm** [comment]
@abravalheri, I got the unit tests running on `master` branch (backported a lot of your stuff to version 3.2) since I think it's rather a bugfix than a new feature release. I will try to make it work also on the `4.0.x` branch.

**Comment by abravalheri** [comment]
Thank you very much @FlorianWilhelm !
