### ISSUE TITLE
Mention pipx

### ISSUE THREAD

**Issue by FlorianWilhelm** [pyscaffold/pyscaffold#248]
Since PyScaffold's `putup` command might be used from any virtual environment or even when no virtual environment is activated, it makes sense to mention [pipx](https://pipxproject.github.io/pipx/) in PyScaffold's documentation. This tool allows you to install putup systemwide in a non-invasive way. We should also add this to our unit tests.

**Comment by jayvdb** [comment]
I see it in the Cirrus `tox_install_script`, but afaics it isnt used in CI yet.

Note that pipx isnt completely isolated. See https://github.com/pipxproject/pipx/issues/233 and https://github.com/pipxproject/pipx/issues/113

**Comment by FlorianWilhelm** [comment]
@jayvdb Right now we only use it to install tox. The question for me is if we should recommend to our users to install PyScaffold using pipx to have it available in all their virtual environments. For me this would be much more convenient. I am not sure this is a good idea though and thus would like to hear some pros and cons.
