### ISSUE TITLE
.gitignore should also exclude .DS_Store for Mac Users

### ISSUE THREAD

**Issue by FlorianWetschoreck** [pyscaffold/pyscaffold#249]
Hi Florian :)

Mac Users always have to gitignore the '.DS_Store' files which are created when one inspects the package folder with the Finder.
And therefore, it would be helpful if you can add '.DS_Store' to the .gitignore template

Best regards,
Florian

**Comment by FlorianWilhelm** [comment]
Hi Florian :-)

Good point, we will add it!

**Comment by FlorianWilhelm** [comment]
Done in fb4aeee9ee80436063fe0fec2e36dd43f9e27b83.

**Comment by FlorianWetschoreck** [comment]
Perfect, thank you :)
