### ISSUE TITLE
Add `docs_requires` similar to `test_requires`

### ISSUE THREAD

**Issue by theHamsta** [pyscaffold/pyscaffold#250]
First, thanks for creating pyscaffold! It's great that I sets up everything automatically and saves me a lot of time.

## Describe your use-case

When I execute `python setup.py test` all requirements configured by `test_requires` get installed.

However, `python setup.py docs` fails if I haven't install sphinx and additional requirements (e.g. sphinx extensions, themes).

## Describe the solution you would like to see for your use-case

Extend the command class for `docs` to install similar to the PyTest command class requirements specified in `setup.cfg` e.g. by a key `docs_requires`.

Currently, I have to configure `extra` and `[options.extras_require]`` in setup.cfg which isn't installed automatically when running `python setup.py docs.`

**Comment by FlorianWilhelm** [comment]
Hi @theHamsta, thanks for your suggestion and feedback, I am glad you like PyScaffold. I like the idea. The challenge is that it would need to be implemented within [setuptools](https://setuptools.readthedocs.io/en/latest/setuptools.html) as PyScaffold only uses the features that setuptools already provides which has many advantages. First of all the codebase of PyScaffold stays small and always compatible. Would you mind to create an issue for that [here](https://github.com/pypa/setuptools).

**Comment by FlorianWilhelm** [comment]
As an alternative, you could also propose this feature for Sphinx since they provide the `BuildDoc` command PyScaffold calls. 

In all cases, PyScaffold would be the wrong place for a feature like that.

**Comment by theHamsta** [comment]
I also thought of making a feature request at Sphinx. However this would have the disadvantage that Sphinx itself could not be installed automatically. A feature request at setuptools should be more general, e.g. set the requirements for arbitary build command. Similar how we can set today the requirements for `entry_points`.

I wanted to have a closer look into how setuptools does this before opening the issue.

**Comment by FlorianWilhelm** [comment]
You could also check out the discussion people are having over test runners and `test_requires`. I am not sure setuptools will keep this feature for much longer. The problem is with setuptools installing things is that you install Python eggs, a really old format which irritates people and can lead to confusion within conda or pip virtual environments. I can imagine that there are rethinking this whole concept right now but I am not sure exactly.
