### ISSUE TITLE
Add Cirrus CI - Flag for core Pyscaffold

### ISSUE THREAD

**Issue by FlorianWilhelm** [pyscaffold/pyscaffold#251]
Travis does not support Windows builds but Cirrus does. PyScaffold is migrated to using Cirrus CI now instead of Travis and thus we should also have a `--cirrus` flag to make it easy for users to set up their projects with Cirrus CI.

A nice `.cirrus.yml` template can be derived from [configupdater](https://github.com/pyscaffold/configupdater/blob/master/.cirrus.yml).

**Comment by FlorianWilhelm** [comment]
To do so adapt also `tox.ini` accordingly.

**Comment by abravalheri** [comment]
Should we always assume tox is present?
