### ISSUE TITLE
Improve Versioning and Git Integration doc section

### ISSUE THREAD

**Issue by Med-All** [pyscaffold/pyscaffold#255]
## Describe your use-case
Improve Versioning and Git Integration doc section. For an example I have no idea how to remove commit id and other values from the build version which looks like

```
python setup.py --version
2.0.0.post0.dev1+g59e85d7

```
instead just 

`2.0.0`

## Describe the solution you would like to see for your use-case
Expand documentation section or create examples.

**Comment by FlorianWilhelm** [comment]
Hi @Med-All, thanks for posting this issue. The documentation refers to [setuptools-scm](https://pypi.org/project/setuptools-scm/) as we are using their functionality, have you read it? In your case, the version string means that you are one commit after the tag 2.0.0. To remove the `.post0.dev1+g59e85d7` part and thus have a _clean_ version string, just tag your current commit with e.g. 2.0.1 and run `python setup.py --version` again. The overall idea is that your releases (which are using `--version` internally) always correspond to your git history, i.e. tags, for reproducibility. Does this help you? How would you extend the docs to make it clearer?

**Comment by Med-All** [comment]
OK, got it but for some reason when I will do 

`python setup.py install`

then doing `application --version` it will tell `unknown`. Should I add something to the setup.cfg to get it to work with the install script?

**Comment by FlorianWilhelm** [comment]
I tried to reproduce it:
1. created a new conda environment and activated it, i.e.
  ```
   conda create -n testing python=3.7
   conda activate testing
  ```
2. Installed pyscaffold with `pip install pyscaffold`
3. Created a scaffold with `putup my_app`
4. Uncommented in `setup.cfg` the lines so that they read:
```
[options.entry_points]
# Add here console scripts like:
# console_scripts =
#     script_name = my_app.module:function
# For example:
console_scripts =
     fibonacci = my_app.skeleton:run
# And any other entry points, for example:
# pyscaffold.cli =
#     awesome = pyscaffoldext.awesome.extension:AwesomeExtension
```
5. Commited with `git commit -a -m "Activated cli command"`
6. Tagged it with `git tag v1.0 -m "v1.0"`
7. Installed it with `python setup.py install`
8. Ran it with `fibonacci --version` and it correctly reports `my_app 1.0`

Could you check again what you are doing? The only case that I know of which would get you an `unknown` is if git is not installed or your scaffold is no longer a git repo (for whatever reasons). This scenario should never occur in practice since the maintainers of Python package create the distribution, i.e. `python setup.py sdist bdist_wheel` from a clean checkout and so should you. The distributions itself then carry the version information in their metadata.

**Comment by Med-All** [comment]
This is what I'm doing:
- Clone project from the BitBucket
- then in the project root folder:
```
[~]$ git --version
git version 1.8.3.1
[~]$ sudo python3 setup.py --version
2.0.0a6
[~]$ sudo python3 setup.py install
running install
...
Finished processing dependencies for MyApp==2.0.0a6
[~]$ /usr/local/bin/myapp --version
My App unknown

```

**Comment by FlorianWilhelm** [comment]
Okay, so you are not using any kind of environments like `conda` or `virtualenv` and just use `sudo` instead to install globally? There are tons of things that could go wrong depending on your system. Have you checked that `python setup.py install` really overwrites `/usr/local/bin/myapp`? Could you post the content of `/usr/local/bin/myapp`, it should only be a few lines. And are you sure that `/usr/local/bin/myapp` is invoked with the same python interpreter you use to set run `python3 setup.py install`?

You could also try running `python3 setup.py sdist` and then install the distribution with `sudo pip3
install dists/myapp...` and see if it works in this case.

In general, you should really think about using virtual environments.

**Comment by Med-All** [comment]
I'm using `virtualenv` on my dev box but when the code goes to the prod is installed globally. 

Here is the output of `/usr/local/bin/myapp`:

```
#!/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'MyApp==2.0.0a7','console_scripts','myapp'
__requires__ = 'MyApp==2.0.0a7'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('MyApp==2.0.0a7', 'console_scripts', 'myapp')()
    )
```

**Comment by FlorianWilhelm** [comment]
I take it that you use the `argparse` code from the PyScaffold example? Can you run `/usr/bin/python3 -m pip list` after the installation and paste the output here? Does it work if you use a virtualenv on the same machine?

@RonnyPfannschmidt, do you have an idea what could go wrong here?

**Comment by Med-All** [comment]
Yes, I'm using `argparse` from the example.

Output for the list:

> certifi (2019.9.11)
> cffi (1.13.1)
> chardet (3.0.4)
> cryptography (2.8)
> DateTime (4.3)
> idna (2.8)
> logging (0.4.9.6)
> pip (9.0.3)
> ProviderDirectory (2.0.0a7)
> pycparser (2.19)
> PyMySQL (0.9.3)
> pytz (2019.3)
> PyYAML (5.1.2)
> requests (2.22.0)
> setuptools (39.2.0)
> six (1.12.0)
> urllib3 (1.25.6)
> zope.interface (4.6.0)

and `--version` works when installed on my dev box `venv`

**Comment by RonnyPfannschmidt** [comment]
how do you get the data for --version? i suspect there is some bug in that part as  it looks like the metadata in the workdir iscoorec

**Comment by Med-All** [comment]
From the git tag on the project and then

`from myapp_v2 import __version__`

and

```
    parser.add_argument(
        "--version",
        action="version",
        version="Provider Directory {ver}".format(ver=__version__))
```

**Comment by RonnyPfannschmidt** [comment]
how do you create that value?

**Comment by Med-All** [comment]
It should to get from the git tag value

**Comment by RonnyPfannschmidt** [comment]
A installed package no longer has git repo, since you don't show the code I assume it's a self inflicted issue

**Comment by Med-All** [comment]
This is what I have done on the destination env:

- Clone project from the BitBucket
- then in the project root folder:

```
[~]$ git --version
git version 1.8.3.1
[~]$ sudo python3 setup.py --version
2.0.0a6
[~]$ sudo python3 setup.py install
running install
...
Finished processing dependencies for MyApp==2.0.0a6
[~]$ /usr/local/bin/myapp --version
My App unknown
```

as for me cloned git repo exists as a local clone

**Comment by FlorianWilhelm** [comment]
Can you please do `python setup py sdist` and then `sudo pip install dist/MyApp... `. This should work.

**Comment by FlorianWilhelm** [comment]
@Med-All: Besides trying my last comment, could you also check out the [documentation about versioning](https://pyscaffold.org/en/latest/features.html#versioning-and-git-integration) that I just extended. Please let me know if this resolves your issue.

**Comment by Med-All** [comment]
OK, I have did that step:

```
Installing collected packages: MyApp
  Found existing installation: MyApp 2.0.0a11+g4373cc3.dirty
    Uninstalling MyApp-2.0.0a11+g4373cc3.dirty:
      Successfully uninstalled MyApp-2.0.0a11+g4373cc3.dirty
  Running setup.py install for MyApp ... done
Successfully installed MyApp-2.0.0b1
```

and then

```
/usr/local/bin/myapp --version
MyApp unknown
```

**Comment by FlorianWilhelm** [comment]
Sorry, it's impossible to debug like this. Could you provide a link to your source code? I could then take a proper look at it.

**Comment by FlorianWilhelm** [comment]
Another thing you could try is to start a Python shell `import myapp` and print `myapp.__version__`. Does this also result in 'unknown'? What makes me really wonder is that `pip` is able to figure out the version of the package and `__version__` doesn't get it.

**Comment by FlorianWilhelm** [comment]
Thinking about it again, I may have found the problem. Could you list the content of `src/myapp/__init__.py`?

**Comment by Med-All** [comment]
Here:

```
# -*- coding: utf-8 -*-
from pkg_resources import get_distribution, DistributionNotFound

try:
    # Change here if project is renamed and does not equal the package name
    dist_name = 'ProviderDirectory-V2'
    __version__ = get_distribution(dist_name).version
except DistributionNotFound:
    __version__ = 'unknown'
finally:
    del get_distribution, DistributionNotFound
```

**Comment by FlorianWilhelm** [comment]
This looks good. Why do you do `from myapp_v2 import __version__` and then 
```
    parser.add_argument(
        "--version",
        action="version",
        version="MyApp {ver}".format(ver=__version__))
```
as it imports from the wrong package? It should read `from myapp import __version__`. Since myapp is the current package right? Can you post the command how you created the scaffold? 

Was it like
```
putup MyApp -p myapp
```

**Comment by Med-All** [comment]
Yes, I have created it as 

```putup MyApp -p myapp```

and then for V2 as

```putup MyApp-V2 -p myapp-v2```

then I have adjusted `setup.cfg` which part to run looks like:

```
console_scripts =
    myapp = myapp_v2.myscriptfile:run
```

**Comment by FlorianWilhelm** [comment]
This becomes really confusing because you are just installing all those different attempts into your system with `myapp` as console_scripts. 

I just tried to reproduce again what you did, i.e. `putup MyApp-V2 -p myapp_v2`, (note the `_` instead of `-` in the package name!) then editing `setup.cfg`, and calling `myapp --version` but it works as expected showing `myapp 0.1.post0.dev1+gf51ec74.dirty`.

Sorry, there seems no way I can help at this point and the problem is almost surely not related to PyScaffold.
