### ISSUE TITLE
setuptools_scm error in Docker

### ISSUE THREAD

**Issue by hershelm** [pyscaffold/pyscaffold#257]
## Description of your problem

When creating a Docker container for my CI process (using Bitbucket pipelines), I've copied the entire directory created using `pyscaffold` into the Docker container, and run the following from inside the Docker container

```python
python setup.py bdist_wheel
```

I get the following error related to setuptools_scm

**Please provide the full traceback.**
```python
+ python setup.py bdist_wheel
Traceback (most recent call last):
  File "setup.py", line 22, in <module>
    setup(use_pyscaffold=True)
  File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.7/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line 447, in __init__
    k: v for k, v in attrs.items()
  File "/usr/local/lib/python3.7/distutils/dist.py", line 292, in __init__
    self.finalize_options()
  File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line 735, in finalize_options
    ep.load()(self, ep.name, value)
  File "/opt/atlassian/pipelines/agent/build/aipl/.eggs/PyScaffold-3.2.3-py3.7.egg/pyscaffold/integration.py", line 105, in pyscaffold_keyword
    version_keyword(dist, keyword, setuptools_scm_config(value))
  File "/opt/atlassian/pipelines/agent/build/aipl/.eggs/PyScaffold-3.2.3-py3.7.egg/pyscaffold/contrib/setuptools_scm/integration.py", line 17, in version_keyword
    dist.metadata.version = get_version(**value)
  File "/opt/atlassian/pipelines/agent/build/aipl/.eggs/PyScaffold-3.2.3-py3.7.egg/pyscaffold/contrib/setuptools_scm/__init__.py", line 150, in get_version
    parsed_version = _do_parse(config)
  File "/opt/atlassian/pipelines/agent/build/aipl/.eggs/PyScaffold-3.2.3-py3.7.egg/pyscaffold/contrib/setuptools_scm/__init__.py", line 113, in _do_parse
    "use git+https://github.com/user/proj.git#egg=proj" % config.absolute_root
LookupError: setuptools-scm was unable to detect version for '/opt/atlassian/pipelines/agent/build/aipl'.
Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
```

**Please provide any additional information below.**

This seems to be related to the issue here:

https://github.com/pypa/setuptools_scm/issues/77

## Versions and main components

* PyScaffold Version: PyScaffold-3.2.3
* Python Version: 3.7
* Operating system: `python:3.7-slim` Docker image
* How did you install PyScaffold: (conda/pip) pip

Has anyone encountered a similar error? What are the recommended practices for building inside of a Docker container?

**Comment by FlorianWilhelm** [comment]
When you run the command your project needs to be a git repository, not just a copy. Better create a package before upload it to some artifact store like devpi and provision your docker container using pip from that artifact store.

**Comment by FlorianWilhelm** [comment]
@hershelm, I just extended the [documentation about versioning](https://pyscaffold.org/en/latest/features.html#versioning-and-git-integration). Please check it out and let me know if this resolves your issue.

**Comment by hershelm** [comment]
Hi @FlorianWilhelm, I appreciate your suggestions and documentation -- thank you :)

I have been able to improve my bitbucket pipeline (similar to the Jenkins pipeline you mentioned, or a Gitlab CI pipeline), which is now able to successfully build my code in the base docker specified (python:3.6), create a dist/*whl artifact, and test my code in another docker image specified by my project's Dockerfile (which installs the artefact, installs all the dependencies, and runs the tests). 

I attempted to make this docker-based "build" and "test" workflow as similar as possible to the one you mentioned in your "versioning and CI" article (just without the artifact store, which I would like to add in later, and using Bitbucket pipelines rather than Jenkins). 

Here is the specification of my bitbucket-pipelines.yml:

```
image: python:3.6

pipelines:
  default:
    - step:
        caches:
          - pip
          - docker
        script: # Modify the commands below to build your repository.
          - cd aipl/
          - docker version
          - python -m pip install setuptools
          - python setup.py bdist_wheel #build
          - docker build -t test . #test
        services:
          - docker
```

The interesting thing is that the build step works with the above docker image specification, but weirdly breaks with other docker images (e.g., `python:3.6-slim` or `continuumio/miniconda3`), reporting the same error as the original post (setuptools_scm versioning). 

I am wondering why we are able to get the versioning info in some docker images but not in others? What would be your recommendations for building when the CI process itself seems to rely on being in a docker container (which I'm guessing copies the source code from the repo, and works in some docker images and not in others). Would appreciate any insight or comments you might have. Thanks.

**Comment by FlorianWilhelm** [comment]
Hi @hershelm, so far I have never used Bitbucket pipelines, which is why I am not 100% certain what's going on. My guess is that `python:3.6-slim` might use another git implementation or at least something is wrong with it. Could you run `git describe --dirty --tags --long --first-parent` (which is basically similar to what `setuptools-scm` does to figure out the version) just before `python setup.py bdist_wheel #build` on the different images and report the errors?

**Comment by hershelm** [comment]
Yes for sure. I ran the pipeline with two images: `python:3.6` and `python:36-slim` just before running `python setup.py bdist_wheel #build`, and interestingly got errors in both cases.

For `python:3.6` (for which `python setup.py bdist_wheel` works), I get

```
+ git describe --dirty --tags --long --first-parent
fatal: No names found, cannot describe anything.
```

For `python:3.6-slim` (for which `python setup.py bdist_wheel` does not work), I get

```
+ git describe --dirty --tags --long --first-parent
bash: git: command not found
```

So I guess `git` doesn't come out of box in the `python:3.6-slim` image.. 

The interesting error is the in the first case (`python:3.6`, because when I run `python setup.py bdist_wheel` without the `git describe` command, it works and returns the following,

```
+ python setup.py bdist_wheel
running bdist_wheel
running build
running build_py
creating build
creating build/lib
creating build/lib/etl
copying aipl/etl/feature_eng.py -> build/lib/etl
copying aipl/etl/preprocessing.py -> build/lib/etl
copying aipl/etl/ingestion.py -> build/lib/etl
copying aipl/etl/__init__.py -> build/lib/etl
copying aipl/etl/_identity.py -> build/lib/etl
creating build/lib/modeling
copying aipl/modeling/<approach_1>.py -> build/lib/modeling
copying aipl/modeling/__init__.py -> build/lib/modeling
copying aipl/modeling/evaluation.py -> build/lib/modeling
copying aipl/modeling/_identity.py -> build/lib/modeling
copying aipl/modeling/<approach_2>.py -> build/lib/modeling
running egg_info
creating aipl/aipl.egg-info
writing aipl/aipl.egg-info/PKG-INFO
writing dependency_links to aipl/aipl.egg-info/dependency_links.txt
writing requirements to aipl/aipl.egg-info/requires.txt
writing top-level names to aipl/aipl.egg-info/top_level.txt
writing manifest file 'aipl/aipl.egg-info/SOURCES.txt'
writing manifest file 'aipl/aipl.egg-info/SOURCES.txt'
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/etl
copying build/lib/etl/feature_eng.py -> build/bdist.linux-x86_64/wheel/etl
copying build/lib/etl/preprocessing.py -> build/bdist.linux-x86_64/wheel/etl
copying build/lib/etl/ingestion.py -> build/bdist.linux-x86_64/wheel/etl
copying build/lib/etl/__init__.py -> build/bdist.linux-x86_64/wheel/etl
copying build/lib/etl/_identity.py -> build/bdist.linux-x86_64/wheel/etl
creating build/bdist.linux-x86_64/wheel/modeling
copying build/lib/modeling/<approach_1>.py -> build/bdist.linux-x86_64/wheel/modeling
copying build/lib/modeling/__init__.py -> build/bdist.linux-x86_64/wheel/modeling
copying build/lib/modeling/evaluation.py -> build/bdist.linux-x86_64/wheel/modeling
copying build/lib/modeling/_identity.py -> build/bdist.linux-x86_64/wheel/modeling
copying build/lib/modeling/<approach_2>.py -> build/bdist.linux-x86_64/wheel/modeling
running install_egg_info
Copying aipl/aipl.egg-info to build/bdist.linux-x86_64/wheel/aipl-0.0.post0.dev50+ga2f5cd2-py3.6.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/aipl-0.0.post0.dev50+ga2f5cd2.dist-info/WHEEL
creating 'dist/aipl-0.0.post0.dev50+ga2f5cd2-py2.py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'etl/__init__.py'
adding 'etl/_identity.py'
adding 'etl/feature_eng.py'
adding 'etl/ingestion.py'
adding 'etl/preprocessing.py'
adding 'modeling/<approach_1>.py'
adding 'modeling/<approach_2>.py'
adding 'modeling/__init__.py'
adding 'modeling/_identity.py'
adding 'modeling/evaluation.py'
adding 'aipl-0.0.post0.dev50+ga2f5cd2.dist-info/METADATA'
adding 'aipl-0.0.post0.dev50+ga2f5cd2.dist-info/WHEEL'
adding 'aipl-0.0.post0.dev50+ga2f5cd2.dist-info/top_level.txt'
adding 'aipl-0.0.post0.dev50+ga2f5cd2.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
/opt/atlassian/pipelines/agent/build/aipl/.eggs/PyScaffold-3.2.3-py3.6.egg/pyscaffold/contrib/setuptools_scm/git.py:68: UserWarning: "/opt/atlassian/pipelines/agent/build" is shallow and may cause errors
  warnings.warn('"%s" is shallow and may cause errors' % (wd.path,))

```

**Comment by FlorianWilhelm** [comment]
Okay, so we found the problem. You need to install git first in the slim docker image.

For the `python-3.6` image the error `fatal: No names found, cannot describe anything.` means that there are no tags that you also see from the version number of your app. This means that whatever Bitbucket operation cloned your repo, it did it without fetching the tags. Some CI services even do crazy things like shallow clones. You could try if a `git fetch origin --tags` works.

**Comment by hershelm** [comment]
Your suggestions have worked nicely, thanks for your help. I was able to install `git` in the `python:3.6-slim` image, run `python setup.py bdist_wheel`, and run the rest of the docker-based CI pipeline successfully, so will close the issue.

Just a quick addition, when using the `python:3.6` image, `git fetch origin --tags` fetched the tags, with the following output:

```
+ git fetch origin --tags
From http://bitbucket.org/noodleai/mother-leaf
 * [new tag]         v0.1-release -> v0.1-release
 ```

However, I get a slightly different error with `git describe`

```
+ git describe --dirty --tags --long --first-parent
fatal: No tags can describe '488c44c54abc252a91127e8185337febd6d2a2e3'.
Try --always, or create some tags.
```

It seems now, it's able to see the SHA, but cannot find the tags to describe it. I added `--always`, and was able to run `git describe --dirty --tags --long --first-parent --always` successfully. Thanks again

**Comment by FlorianWilhelm** [comment]
Hi @hershelm, thanks for pointing out the usage of `--always` in `git describe --dirty --tags --long --first-parent --always`. You can remove this command again when everything works since it was just for debugging. 

BTW, could you describe how you create tags? In git, there are two kinds of tags **lightweight** and **annotated** which are different.
