### ISSUE TITLE
Add documentation on how to get rid of "+[hash].dirty" in version name

### ISSUE THREAD

**Issue by LeviBorodenko** [pyscaffold/pyscaffold#258]
## Describe your use-case
I have a project and following the [documentation](https://pyscaffold.org/en/latest/features.html#versioning-and-git-integration) on how to obtain a clean version, I commit all my changes and tag them via  `git tag v0.9.2`.

However, if I run `python setup.py --version` right after, I get `0.9.2+ge50bbc0.dirty` instead of the desired `0.9.2`. It is not clear to me how to get rid of the .dirty suffix and the hash.

## Describe the solution you would like to see for your use-case
I believe this issue could be fairly common and once I know how to get a clean version name in that case, I would like to add my solution to the documentation.

**Comment by FlorianWilhelm** [comment]
Hi @LeviBorodenko, could you show the output of `git status`, `git log` and `git describe --dirty --tags --long --first-parent`?

**Comment by LeviBorodenko** [comment]
Sure thing.

## git status

```
On branch master
Your branch is up-to-date with 'origin/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    No_such_file.lanced
	deleted:    requirements.txt
	modified:   setup.cfg

no changes added to commit (use "git add" and/or "git commit -a")
```

## git log

```
commit e50bbc0601217504a49a40892526a83ad53aff83 (HEAD -> master, tag: v0.9.2, origin/master, v0.9.2)
Author: Levi Borodenko <Levi.borodenko@gmail.com>
Date:   Wed Nov 13 21:59:02 2019 +0000

    [....]

commit 9b99e00447913a31b0363291ddb68c034502ba53
Author: Levi Borodenko <Levi.borodenko@gmail.com>
Date:   Wed Nov 13 21:20:37 2019 +0000

    [....]

commit c258d6f8fa39fb7928342ad95b436f1d824a264f
Author: Levi Borodenko <Levi.borodenko@gmail.com>
Date:   Wed Nov 13 21:12:40 2019 +0000

    [....]

commit 2f696d70d50b5145efe6cd06ada56313f0800452 (tag: v0.9.1)
Author: Levi Borodenko <Levi.borodenko@gmail.com>
Date:   Wed Nov 13 14:57:54 2019 +0000

   [....]

commit 7e12b0da60dcefcd546a11d78fc0eb5715113c8f
Author: Levi Borodenko <Levi.borodenko@gmail.com>
Date:   Wed Nov 13 11:59:56 2019 +0000

    [....]

commit d90be3bd00525fc5a6e97eb97b729842e4795f76 (tag: v0.9.0)
Author: Levi Borodenko <Levi.borodenko@gmail.com>
Date:   Tue Nov 12 21:33:09 2019 +0000

    [....]

```

## git describe --dirty --tags --long --first-parent 
```
v0.9.2-0-ge50bbc0-dirty
```

**Comment by FlorianWilhelm** [comment]
Your `git status` command shows that you deleted some files and did not commit those changes. This is why your workspace is dirty which is also what `git describe ...` shows.

**Comment by LeviBorodenko** [comment]
Ok, I think I found the culprit. The issue was the two files listed in git status as "Changes not staged for commit". To get rid of them, I ran `git add -u .`  which  removes as well as modifies index entries to match the working tree. After committing and re-tagging, I got the desired clean version. Thank you very much.

**Comment by FlorianWilhelm** [comment]
You are welcome. Closing this issue.
