### ISSUE TITLE
Allow to override local_scheme of setuptools_scm

### ISSUE THREAD

**Issue by tarioch** [pyscaffold/pyscaffold#260]
## Describe your use-case
As I would like to push every commit on a branch to testpypi I need to disable the local_scheme. See 
https://github.com/pypa/setuptools_scm/issues/342
as far as I can tell it's currently not possible to do this if pyscaffold is used

**Comment by FlorianWilhelm** [comment]
@tarioch, since PyScaffold more or less just uses `setuptools_scm` you can pass the same arguments to the `use_pyscaffold` keyword as you would to `use_scm_version`. 

In your case make sure that you change `setup.py` to:
```
 import sys

 from pkg_resources import VersionConflict, require
 from setuptools import setup

 try:
     require('setuptools>=38.3')
 except VersionConflict:
     print("Error: version of setuptools is too old (<38.3)!")
     sys.exit(1)


 def local_scheme(version):
     return ""


 if __name__ == "__main__":
     setup(use_pyscaffold={"local_scheme": local_scheme})
```
