### ISSUE TITLE
Windows documentation should specify running [conda init] to avoid superficial git errors

### ISSUE THREAD

**Issue by kalingibbons** [pyscaffold/pyscaffold#265]
## Windows conda-forge install without conda (userspace) modifying path
Installed miniconda in user space on Windows, following recommendations to not modify the path and launch through the Anaconda prompts. Was getting the `putup` error about making sure the `git` binary was on my system path. Git worked fine for all shells installed, and was in the system path.

## Adding a suggestion to run `conda init` if git is working and `putup` will not recognize
The documentation suggested running the `putup` command using the git bash shell, so I ran `conda init bash` in order to make this possible. This worked, so I also ran the command for powershell and now everything is working correctly.

**Comment by kalingibbons** [comment]
Did not work for a second computer. I'll close this.

**Comment by FlorianWilhelm** [comment]
@kalingibbons, thanks for this suggestion. So `conda init` does not always solve it? How did you solve it on your second computer? We are really open for additions to our documentations like this. Also, most of the maintainers are either Linux or Mac users, so Windows is kind of underrepresented and thus support is highly appreciated.

**Comment by kalingibbons** [comment]
Actually, I kept trying after I closed that issue and it is at least related to solving the problem. I tried running `conda init powershell` and `conda init bash` a few different times with shell restarts inbetween, and did at least one `conda init --reverse` within a powershell instance. Eventually something stuck and putup worked on the work computer. Sorry that's not a very repeatable description!

**Comment by kalingibbons** [comment]
I guess I should reopen this issue, since `conda init` was still related to the issue.

**Comment by FlorianWilhelm** [comment]
@kalingibbons, thank you. Could you describe wherein our docs you would add which statement to help Windows users with conda?

**Comment by kalingibbons** [comment]
Honestly enough time went by since I got it working that I've forgotten and I won't be able to give a good answer. Sorry about that, Florian. I'll close the ticket.
