### ISSUE TITLE
Option to strip "coding: utf-8" headers

### ISSUE THREAD

**Issue by maresb** [pyscaffold/pyscaffold#266]
Hi, I'm looking at `pyscaffold` for the first time. As someone who writes Python exclusively for version 3, my understanding is that
```
# -*- coding: utf-8 -*-
```
is a relic of Python 2 and is redundant since utf-8 is default in version 3.  Including this header doesn't harm anything, but I never use it in my own files (should I???), so it feels like clutter, or at least in conflict with my personal coding conventions.

Would it be possible to specify a command-line argument to `putup` (like `-v3`) which automatically strips this header from all files?  Thanks!

**Comment by FlorianWilhelm** [comment]
Good point, we will fix this in version 4.

**Comment by abravalheri** [comment]
Done in #298
