### ISSUE TITLE
More Pypi Links

### ISSUE THREAD

**Issue by FlorianWilhelm** [pyscaffold/pyscaffold#268]
Add more projcets links to the setup.cfg template, e.g. tracker, source, homepage etc. like under https://pypi.org/project/yellowbrick/

**Comment by abravalheri** [comment]
I have added the links in the commit https://github.com/pyscaffold/pyscaffold/commit/0d32e7ec7e02c2d28f598a1369313885425d8600

I hope that is what you had in mind...

**Comment by FlorianWilhelm** [comment]
@abravalheri Yes, that's exactly it! Thank you :-)
