### ISSUE TITLE
How does the Package and Files Data feature work?

### ISSUE THREAD

**Issue by bravegag** [pyscaffold/pyscaffold#275]
Hello, I've read the relevant `Package and Files Data` section of the following document but still doesn't work for me:
https://readthedocs.org/projects/pyscaffold/downloads/pdf/latest/ 

My setup is the following:
1. install PyScaffold 2.3
2. `pupup myproject `
3. Added a `config` folder to contain INI configuration files that I need executables to access equally from development or released versions. My project structure looks like:
```
myproject
--- src
------ config
--------- myfile1.ini
--------- myfile2.ini
------ myproject
--------- packages
```
4. modified `setup.cfg` to uncomment / add:
```
...
include_package_data = True
...
[files]
packages = 
        myproject
data_files =
        config = config/*
```

When I say it doesn't work (and assuming that I don't have uncommitted local changes) I mean that running `pip install .` doesn't copy over `config` to the `Lib/site-packages/myproject-xxx`. Therefore my code working in development will see this folder but it wont while running in bwheel released mode since the configuration data files are not being copied.

I think the feature Package and Files Data is very important but in the documentation a lot is left to the imagination e.g. "Additional data files are defined as key value pairs of source and target". It doesn't say where the data files are expected to be placed precisely. It doesn't say whether these files are going to be copied over to the dist folder. It also doesn't say what these source and targets are? also, are these files or folders? where are the target folders copied to? 

I have tried many different variations where to place the `config` folder and setting the `data_files` entry but doesn't seem to have an effect.

**Comment by FlorianWilhelm** [comment]
In document you mention it says:
![image](https://user-images.githubusercontent.com/3184072/79603002-d1938f80-80eb-11ea-8c87-26e5f110d89d.png)
You have to put your `config` folder into your package, i.e. `myproject` folder. Could you make a PR with a formulation that makes this clearer? Thanks!

**Comment by bravegag** [comment]
@FlorianWilhelm 

Thank you for the quick reply! and apologies for taking me a while to respond. I had all code and use case inside the office which has no connection to the outside world. I have setup a MVCE replicating what I mean and intend to do.

Please find the code here:
https://github.com/bravegag/sampleproj

and the specific use-case that doesn't work summarized in the changes of this commit:
https://github.com/bravegag/sampleproj/commit/85cfafecb91972c31385ac6ce16c61901bf6fe1c

To replicate simply check out and then do (to setup local development or even without the -e):
```
pip install -e .
fibonacci 4 -vv
```

Leads to the output and error:
```
(base) bravegag@Zeus:~/code/sampleproj$ fibonacci 4 -vv
[2020-04-20 14:53:38] DEBUG:sampleproj.skeleton:Starting crazy calculations...
The 4-th Fibonacci number is 3
Traceback (most recent call last):
  File "/opt/dev/anaconda3/bin/fibonacci", line 11, in <module>
    load_entry_point('sampleproj', 'console_scripts', 'fibonacci')()
  File "/home/bravegag/code/sampleproj/src/sampleproj/skeleton.py", line 122, in run
    main(sys.argv[1:])
  File "/home/bravegag/code/sampleproj/src/sampleproj/skeleton.py", line 110, in main
    config.read(read_text("sampleproj", "config/test.ini"))
  File "/opt/dev/anaconda3/lib/python3.7/importlib/resources.py", line 167, in read_text
    resource = _normalize_path(resource)
  File "/opt/dev/anaconda3/lib/python3.7/importlib/resources.py", line 61, in _normalize_path
    raise ValueError('{!r} must be only a file name'.format(path))
ValueError: 'config/test.ini' must be only a file name
```

**Comment by FlorianWilhelm** [comment]
This might actually be a fault in my documentation. Could you try instead:
```
read_text("sampleproj.config", "test.ini")
```
I mean the error message clearly states that `config/test.ini` must be a file name but is none.

**Comment by bravegag** [comment]
@FlorianWilhelm still doesn't work ... I have added your fix suggestion and now I get the following error:
```
(base) bravegag@Zeus:~/code/sampleproj$ fibonacci 4 -vv
[2020-04-21 07:14:38] DEBUG:sampleproj.skeleton:Starting crazy calculations...
The 4-th Fibonacci number is 3
Traceback (most recent call last):
  File "/opt/dev/anaconda3/bin/fibonacci", line 11, in <module>
    load_entry_point('sampleproj', 'console_scripts', 'fibonacci')()
  File "/home/bravegag/code/sampleproj/src/sampleproj/skeleton.py", line 122, in run
    main(sys.argv[1:])
  File "/home/bravegag/code/sampleproj/src/sampleproj/skeleton.py", line 110, in main
    config.read(read_text("sampleproj.config", "test.ini"))
  File "/opt/dev/anaconda3/lib/python3.7/importlib/resources.py", line 169, in read_text
    with open_text(package, resource, encoding, errors) as fp:
  File "/opt/dev/anaconda3/lib/python3.7/importlib/resources.py", line 126, in open_text
    _check_location(package)
  File "/opt/dev/anaconda3/lib/python3.7/importlib/resources.py", line 82, in _check_location
    raise FileNotFoundError(f'Package has no location {package!r}')
FileNotFoundError: Package has no location <module 'sampleproj.config' (namespace)>
```

**Comment by FlorianWilhelm** [comment]
You are missing the `__init__.py` file inside `sampleproj/src/sampleproj/config/`, that's why Python doesn't recognize it as a package.

**Comment by FlorianWilhelm** [comment]
This issue was answered.
