### ISSUE TITLE
Broken link to Pipenv

### ISSUE THREAD

**Issue by louwers** [pyscaffold/pyscaffold#276]
https://github.com/pyscaffold/pyscaffold/blob/master/docs/dependencies.rst

The link to Pipenv is broken.

**Comment by abravalheri** [comment]
Thanks @louwers, I will update the link.

**Comment by abravalheri** [comment]
Thanks @louwers, I will update the link.

**Comment by abravalheri** [comment]
Thanks @louwers, I will update the link.

**Comment by FlorianWilhelm** [comment]
Thanks @louwers for reporting.
