### ISSUE TITLE
include_package_data = False is ignored

### ISSUE THREAD

**Issue by lucacerone** [pyscaffold/pyscaffold#278]
## Description of your problem

I am developing a Python package, whose directory structure has been laid out with Pyscaffold.
The repository contains some directory and files that I do not want to include in the actual
package (e.g. the Dockerfile for the container, the folder for CI/CD etc. etc.) but that I do need under version control.

I set `include_package_data = False` but all the files under version control are actually included in the package when I run

```bash
python setup.py sdist
```

I am sure it's just a misunderstanding on my side, but how can I let setuptools/pyscaffold
only include certain folders and not others?
I have also tried to set 

[options.exclude_package_data]
* = *

but regardless all the folders in the repository end up in the sdist package archive

**Please provide a minimal, self-contained, and reproducible example.**
```python
python setup.py develop
```

**Please provide the full traceback.**
```python
[The error output here]
```

**Please provide any additional information below.**

## Versions and main components

* PyScaffold Version: 3.2.3
* Python Version: 3.7
* Operating system: MacOS
* How did you install PyScaffold: pipx

**Comment by lucacerone** [comment]
OK, so after reading carefully the setuptools documentation, I think the issue I am having is related to having the file `src/package_name.egg-info/SOURCES.txt`.

In the documentation they mention:


> When building an sdist, the datafiles are also drawn from the package_name.egg- info/SOURCES.txt file, so make sure that this is removed if the setup.py package_data list is updated before calling setup.py.

I have tried to remove it manually, but every time I run `python setup.py sdist` the folder is created again and SOURCES.txt is in it, so it copies all the files in the repository in the final package.

How can I prevent this from happening? Should I set something in setup.cfg?

**Comment by lucacerone** [comment]
OK, I finally figured that a MANIFEST.in file has to be created and this is actually not a pyscaffold issue at all. My bad for opening a ticket.

**Comment by lucacerone** [comment]
In case anyone bumps into this issue:

the file SOURCES.txt in the src/packaage.egg-info folder is created using the directives in the MANIFEST.in template.
If no MANIFEST.in is available, all the content of the folder is added to the final sdist package.

**Comment by FlorianWilhelm** [comment]
Hi @lucacerone, thanks for posting this issue. You solved it using `MANIFEST.in` which is fine but actually it should also work by just setting 
`include_package_data = False`
Since it doens't this is a bug I guess. Most likely somehow related to `setuptools_scm`. I am currently quite busy but we keep this ticket to check it later.

**Comment by abravalheri** [comment]
@FlorianWilhelm could this be related to https://github.com/pypa/setuptools/issues/1461?

**Comment by FlorianWilhelm** [comment]
@abravalheri I am not so sure. I mean files are included although we don't specify `Manifest.in`. Maybe it really is related to the old setuptools_scm version we have vendorized.

**Comment by lucacerone** [comment]
Hi @FlorianWilhelm and @abravalheri, many thanks for looking into this.

To be honest, I found the documentation around this a bit confusing, both in PyScaffold and setuptools, so I wasn't quite sure what I should expect.

In general, if there were no bug, how could I get a package to include all files under  version control in src/package/ (I plan to place everything my package needs there, so that it's clear I want them available with my package) and leave all other files out of it?

Is there any cons using Manifest.in for the time being?

**Comment by abravalheri** [comment]
@lucacerone, if you are willing to go for Manifest.in I don't see many cons (but Florian definitely knows better). Manifest.in is just harder to maintain than relying on the version control and file sytem.

By the way, I just release a pre version of PyScaffold  v3.3 with the most up-to-date setuptools_scm, so in theory, there is either no bug left, or it is a setuptools/setuptools_scm bug.
If you want to test it, we would love to have your feedback.

**Comment by lucacerone** [comment]
@abravalheri many thanks! I am on holidays right now, but I will give it a try in a couple of weeks!

**Comment by FlorianWilhelm** [comment]
I just gave it a test run, here is what I did:

```
conda create -n pyscaffold3.3 python=3.8
conda activate pyscaffold3.3
pip install --pre pyscaffold==3.3a1
putup include_pkg_test
cd include_pkg_test
echo "CONTENT" > src/include_pkg_test/data.txt
git add src/include_pkg_test/data.txt
git commit -a -m "Added content file"
python setup.py sdist 
```
and the output shows that data.txt is part of the distribution as expected.

Now I set `include_package_data = False` in `setup.cfg`, did `rm -rf dist build` and reran `python setup.py sdist`. The output still shows `data.txt` as part of the distribution which is not expected. 

Doing exactly the same as above but running `python setup.py bdist_wheel` achieves the expected results. For me, this rather looks like a bug in setuptools.

**Comment by FlorianWilhelm** [comment]
Also a [EuroPython 2015 talk](https://ep2015.europython.eu/media/conference/slides/less-known-packaging-features-and-tricks.pdf) states that only `bdist_wheel` seems to care about the value of `include_package_data`. In case of `sdist` everything under version control will be packaged. 

The main question here is why would you put a file under `src/pkg_name` and in version control when you don't want it to be packaged? Just put it for instance under any non-package directory like `files` or even `src/files`. In this case, it will not be packaged even when under version control. Maybe this should just be noted in the docs but I don't see any point in adding a `MANIFEST.in` just for this little pathological case that even makes no real sense.

**Comment by abravalheri** [comment]
Thank you very much @FlorianWilhelm for testing it! I will see if I can summarise this in the docs.

 Just one note: with the adoption of `packages = find_namespace:` in v4, I suppose everything under `src` will be considered a package, even when they don't have a `__init__.py`. So if anyone really wants to have these files in the repository but not as part of the distribution, the best option is to put a folder (e.g. `files`) right at the root of the project, or to exclude it explicitly via `[options.packages.find] exclude` in `setup.cfg`.

**Comment by FlorianWilhelm** [comment]
Yes, I think writing this in the docs just like you did is the best option @abravalheri. People will then find it when they read the docs and we should not support a confusing approach (like having files in `src` and git but not in the distro) anyway.

**Comment by lucacerone** [comment]
> @lucacerone, if you are willing to go for Manifest.in I don't see many cons (but Florian definitely knows better). Manifest.in is just harder to maintain than relying on the version control and file sytem.
> 
> By the way, I just release a pre version of PyScaffold [v3.3](https://pypi.org/project/PyScaffold/3.3a1/#files) with the most up-to-date setuptools_scm, so in theory, there is either no bug left, or it is a setuptools/setuptools_scm bug.
> If you want to test it, we would love to have your feedback.

Thanks @abravalheri ! I am on holidays and not able to try, but I'll definitely test it when I am back in a couple of weeks!

**Comment by lucacerone** [comment]
> Yes, I think writing this in the docs just like you did is the best option @abravalheri. People will then find it when they read the docs and we should not support a confusing approach (like having files in `src` and git but not in the distro) anyway.

Many thanks for your test @FlorianWilhelm!

For me documenting clearly the expected behavior, and the best approach is perfectly fine.

The issue I was having, however, was with directories outside of src (e.g.a docker folder),
without using Manifest.ini I wasn't able to exclude them from the final zip (I never tried wheels myself, but I will).

**Comment by abravalheri** [comment]
Hi @lucacerone please feel free to re-open the issue if you find something missing. I have the feeling though that if there is something left it would end up being a problem in setuptools.

This thing with the `zip` file is curious... I suppose by `zip` you mean a `sdist` distribution? `sdist`s should not include files from outside the `src` folder.... `bdist`s on the other hand are different bests, very outdated and difficult to deal... That is why the official guides recommendation is to use `bdist_wheel`.
