### ISSUE TITLE
I created a video with how to use PyScaffold... can we link to it in the README, or in the docs?

### ISSUE THREAD

**Issue by Laurentiu-Andronache** [pyscaffold/pyscaffold#280]
Here it is: https://www.youtube.com/watch?v=JwwlRkLKj7o

Or if you'd rather change something to how I followed the process, let me know and I might remake the video.

**Comment by FlorianWilhelm** [comment]
Hi @Laurentiu-Andronache, thanks a lot, this is awesome! Could you just make a PR for the docs and link your video?

**Comment by Laurentiu-Andronache** [comment]
I don't know in what section to add it there...

**Comment by FlorianWilhelm** [comment]
I added the reference to your video tutorial on the main page of the PyScaffold documentation. Thanks again.
