### ISSUE TITLE
coverage combine .coverage => "No usable data files" in Cirrus CI

### ISSUE THREAD

**Issue by abravalheri** [pyscaffold/pyscaffold#285]
For some reason coverage keeps breaking on master...

Even a [newly generated project with a .cirrus-ci.yml](https://github.com/pyscaffold/ci-tester) very similar to PyScaffold's and configupdater (it was generated with the new cirrus extension proposed in #284) [breaks](https://cirrus-ci.com/github/pyscaffold/ci-tester).

Interestingly, everything seems [fine](https://coveralls.io/github/pyscaffold/ci-tester) with [travis](https://travis-ci.org/github/pyscaffold/ci-tester).

**Comment by FlorianWilhelm** [comment]
I got the same problem running it locally

**Comment by FlorianWilhelm** [comment]
I just updated `configupdate` as a user who uses it independently of PyScaffold found some bugs. I had the same problem with coverage as you describe and fixed it by just commenting `coverage combine...`. It seems like it is no longer needed maybe?

**Comment by abravalheri** [comment]
Thank you very much @FlorianWilhelm, it seems that now pytest-cov takes care of that.
