### ISSUE TITLE
SPDX license identifiers?

### ISSUE THREAD

**Issue by abravalheri** [pyscaffold/pyscaffold#319]
Should we use [SPDX](https://spdx.org/licenses/) license identifiers (specially in the corresponding field in `setup.cfg`)?

I think they are not currently standardised in Python, right? But it does make sense to use something is endorsed by linux foundation.

**Comment by FlorianWilhelm** [comment]
I think it makes sense to use them. That means one would have to change the identifiers in `templates.__init__.py` according to their list, right?

**Comment by abravalheri** [comment]
Yes, I suppose only changing the keys in the dictionary with the license is enough is terms of implementation (+ docs as you mentioned).

**Comment by abravalheri** [comment]
Something more complicated and probably not necessary would be using the files directly from their [repository](https://github.com/spdx/license-list-data), but since they do not naively support the string interpolation we do, it would be not as nice.

**Comment by FlorianWilhelm** [comment]
Thanks! I think this is the best solution and not relying on internet access is really important for many users of PyScaffold I guess.
