### ISSUE TITLE
Broken link to pytest

### ISSUE THREAD

**Issue by jochengietzen** [pyscaffold/pyscaffold#327]
## Description of your problem

Pytest seems to have moved their documentation website. The old vs. the current one are as follows:
old:
https://pytest.org/latest/plugins.html
new:
https://docs.pytest.org/en/latest/plugins.html

https://github.com/pyscaffold/pyscaffold/blob/0fd91711061d76f46fc931e8e0914464ae347cae/src/pyscaffold/templates/conftest_py.template#L7

* PyScaffold Version: Version: 3.2.3
* How did you install PyScaffold: pip

**Comment by abravalheri** [comment]
Hi @jochengietzen  thank you very much for pointing out this problem.

It seems that the documentation is accessible from both URL though... The difference is that https://pytest.org/latest/plugins.html actually redirects to "stable".

Is there any reason to prefer the "docs" subdomain?

**Comment by jochengietzen** [comment]
Hi @abravalheri,
Thank you for your response! 
I am sorry for the confusion. By the time I posted this issue I am pretty sure, that the link didn't work. I even tried it with 3 Browsers and a different network before posting 🤔 
Anyway, I don't think there is a necessity for it to be directed to the docs subdomain, if the original works.

Thank you for taking the time to look into it and sorry for my late response. My Mailbox was flooded and I didn't see your answer immediately.

**Comment by abravalheri** [comment]
No problems  @jochengietzen . I did update the URL in the development branch anyway. I hope that is the more future proof option...
