### ISSUE TITLE
Allow to set different copyright holder then author

### ISSUE THREAD

**Issue by CarliJoy** [pyscaffold/pyscaffold#334]
## Describe your use-case
I am using pyscaffold to establish sane standards at my company. There are a lot of engineers that use python mainly for scripting but their scripts will be used at some point or another as proper application.
Therefore I am trying to automate as much as possible to help this engineers creating packages. I created an internal pyscaffoldext to do this. Works quite good. Thanks for this great extension!

One thing I am struggling with is that the copyright in the Documentation and the license.txt is set to the git user.
So I need to advice to users to change all Copyright notes (in Sphinx and the License) with the Company name manually after creating the project ....

## Describe the solution you would like to see for your use-case
I would like to have the possibility to define/overwrite a "copyright_owner" (in my case it would be the companies name) in my extension.
So there would be the need to add a new replacement parameter `${copyright_holder}` that defaults to `${author}` if nothing else given.
Of course the templates would have to be updated in all relevant places.

**Comment by CarliJoy** [comment]
It just came to my mind, that replacing "${year} ${author}" or "{year}, ${author}" in the templates with "{copright_string}" could help maintaining a project.
On a new year, a user simply could run:
`putup --update --copyright_string "2020-2021, Author"`
and all respective files could be updated...

**Comment by FlorianWilhelm** [comment]
Hi @CarliJoy, thanks for your proposal. For me, that makes a lot of sense, especially in a company environment. 
Would it work for you if you just hard-coded the name of your company in your PyScaffold extension in such a way that after the initial structure is defined you just call the template functions for license.txt and Sphinx's conf.py again but this time passing `author = "Your Company"`? This way you could also enforce the type of license, even providing your own specific. 

Check out [the source code of pyscaffoldext-dsproject](https://github.com/pyscaffold/pyscaffoldext-dsproject/blob/master/src/pyscaffoldext/dsproject/extension.py). Here for instance the default `environment.yaml` is redefined using other options. Does this help you?

**Comment by CarliJoy** [comment]
Dear @FlorianWilhelm,

thanks for your answer, Yep only generating a fixed layout with a fixed license would be possible and would also close my use case. 
Still I think introducing a "copyright_string" would a nice idea? If I find time I could start coding and create a PR, would that something you would consider merging?

**Comment by FlorianWilhelm** [comment]
Thanks, @CarliJoy for your proposal. I am not sure if it should be part of PyScaffold itself since I ask myself how many people would actually use it? And in the end, it's only a few small changes in the license file and documentation. Hearing from your use-case where you need an extension anyway, my gut feeling says that this option should consequently not be part of the core. But that's only my 5cent. What does @abravalheri think about it?

**Comment by abravalheri** [comment]
Hello guys, nice to see we have this conversation going on. I agree that including this option in the core of PyScaffold seems a bit overkill.

The nice thing about Florian's suggestion is that if you are already making an extension for the company, you can literally add an action to search and replace the contents of the `LICENSE.txt`.

On top of that, at least in v4 it should be very easy to [make an extension that automatically activates others](https://pyscaffold.org/en/v4.0.x/api/pyscaffold.extensions.html#pyscaffold.extensions.include), so your "company extension" could for example automatically add `--pre-commit`, `--cirrus-ci` and etc...

@CarliJoy, an alternative that I can think by reading your use case, if you are interested, would be creating and external extension (`pyscaffoldext-...`)  to automatically update the dates in the license, and take also the opportunity to update the copyright holders... I would happily review it if it is offered to the PyScaffold community.

**Comment by CarliJoy** [comment]
Dear @abravalheri,

I will think about this extension if I find some time, I might write it.
But this will be probably only after Version 4 was released.

Still so far I see this issue as resolved.

BR

Carli*
