### ISSUE TITLE
Move isort settings to pyproject.toml [4.x]

### ISSUE THREAD

**Issue by CarliJoy** [pyscaffold/pyscaffold#336]
## Describe your use-case
There is a deciated isort.cfg file but no other tool (besides pre-commit) has its one config file, thats confusing.

Also isort.cfg only get added if --pre-commit is used. 

## Describe the solution you would like to see for your use-case
Add the isort.cfg into `pyproject.toml` or `setup.cfg` (both possible according to https://pycqa.github.io/isort/docs/configuration/config_files/)

Then it would be also okay (IMO) to include the settings by default in the pyproject.toml because they are related to the other tools (black for instance) used by the template.

IMO that would be the best and easiest solution:
- remove the isort.cfg and move the content to the default pyproject.toml

**Comment by CarliJoy** [comment]
I could create a PR if I you are okay with the procedure @FlorianWilhelm

**Comment by abravalheri** [comment]
Hi @CarliJoy, thank you for bringing this discussion forward. I agree with you that the way things are right now is definitely not the most "uniform" or "ideal" way of doing things, however I would argue that it is the more pragmatic 😝

For the version 4, I think we are still committing to provide people a escape hatch from isolated builds so they can still do some old fashion packages while things are not stable enough (via `--no-pyproject`). In that case, working conditionally with the flags and trying to assertively position the configuration for isort would result (in my opinion) in added complexity.

We could also try other alternatives like using `setup.cfg` or `tox.ini`, but then the future of these files are uncertain...

By the way, we do have some individual files for other tools like `tox.ini`, `.coveragerc`, `.travis.yml`, `.cirrus.yml`. Do you think `.isort.cfg` is particularly confusing?
