### ISSUE TITLE
Auto Add 

### ISSUE THREAD

**Issue by CarliJoy** [pyscaffold/pyscaffold#338]
## Describe your use-case
pre-commit is only useful when people have it activated by default.
It is easy to forget when cloning a repro.

## Describe the solution you would like to see for your use-case
pre-commit can now be activated by default:
https://pre-commit.com/#automatically-enabling-pre-commit-on-repositories

**Comment by CarliJoy** [comment]
Sorry misunderstood the configuration. 
That is a system-wide setting not a repro setting.
So not related to pyscaffold (next time I should test things first ;-))

**Comment by abravalheri** [comment]
Thank you very much @CarliJoy, I will try to integrate this as a piece of documentation.

In version 4, I am trying my best to activate the pre-commit by default, but that will only work when you create the project using `putup`, not when you clone the repository and try to contribute.

For that scenario, I also tried to add some documentation to the generated `README`.

Another action taken is to add `pre-commit run --all-files` to the CI. While we still trust the user to manually activate it, it is form of "damage control"...
