### ISSUE TITLE
Replace `pip intall -e . ` by `python setup.py develop` if we go for pyproject.toml

### ISSUE THREAD

**Issue by FlorianWilhelm** [pyscaffold/pyscaffold#341]
If we go for using `pyproject.toml` (and I think there is much consent here), we have to check that the docs mentions that `pip install -e` doesn't work and `python setup.py develop` is the alternative for it.

**Comment by FlorianWilhelm** [comment]
@abravalheri, I guess you would recommend doing this as an internal extension like `--rtd`? Or is it so common that everyone would want to have these two files anyway?

**Comment by abravalheri** [comment]
Hi @FlorianWilhelm, I don't know if the last 2 comments are about the same topic, but regarding the read the docs and conda environment files, I thing we can add those files anyway... It should be fairly common. If people don't like them they can delete the files or not bother to configure rtd...

**Comment by FlorianWilhelm** [comment]
@abravalheri, sorry, my comment was meant for another thread.

**Comment by abravalheri** [comment]
I suppose in a near future `pip install -e` will work with `pyproject.toml` (as soon as the community figure out a PEP for editable installs compatible with PEP 517/518, I know they are working with that), and I suspect `python setup.py` will become more and more unused until it is deprecated...

Last time I tried `pip install -e .` with a PEP517 compatible project it worked, as long as the stub `setup.py` file is present, which is the case for the projects generated in v4.

**Comment by FlorianWilhelm** [comment]
Okay, cool! Then it's better to leave it as it is. So this issue can be closed?

**Comment by abravalheri** [comment]
Yes I agree.

For the time being let's leave as it is. If we get any issue reported we might revise it ;)
