### ISSUE TITLE
Add `.readthedocs.yaml` and `docs/environment.yaml` to PyScaffold to better support ReadTheDocs

### ISSUE THREAD

**Issue by FlorianWilhelm** [pyscaffold/pyscaffold#346]
ReadTheDocs improved a lot in the last years and nowadays a lot of configuration can be done via `.readthedocs.yaml`. Also conda environments are finally possible and we should provide a default `docs/environment.yaml` with the correspondingly configured `.readthedocs.yaml` to allow users to easily publish their docs on RTD.

**Comment by FlorianWilhelm** [comment]
@abravalheri Since RTD is pretty standard and there is no real competitor, one could also think about adding `.readthedocs.yaml` and `docs/environment.yaml` by default?

**Comment by abravalheri** [comment]
Hi Florian, yes I think leaving it by default should be OK.

**Comment by FlorianWilhelm** [comment]
This is done in #340
