### ISSUE TITLE
Move Travis extension to its own repository (external extension)

### ISSUE THREAD

**Issue by abravalheri** [pyscaffold/pyscaffold#355]
There is probably some errors in the CI configuration for [pyscaffoldext-django](https://travis-ci.org/github/pyscaffold/pyscaffoldext-django) and [pyscaffoldext-cookiecutter](https://travis-ci.org/github/pyscaffold/pyscaffoldext-cookiecutter), which means that the `travis` builtin extension needs some care. I don't think it is an error in PyScaffold code itself, but from time to time we always need to review the test environment configuration or fix problems in the test suites that never showed up before...

**Comment by FlorianWilhelm** [comment]
Should these plugins also be moved to cirrus?

**Comment by abravalheri** [comment]
They definetely can, but one of the reasons why I kept then on travis was to keep an eye on the travis extension :P 
(i.e. see when it have a bug and needs fixing).

Maybe having the 2 CIs configured for the repos is a nice idea, because then we can have a clear understanding if the extensions are broken or if the travis config is broken...

**Comment by abravalheri** [comment]
Ok, forget about that, I just found that Travis is adopting changes in the [pricing model](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing).

I understand that they need to thrive as a company and that they still are trying to keep supporting the open source community. I don't mind having to go through the technical support team to get approval for FOSS projects, but having to estimate an allotment of credits beforehand and having to constantly renew it once it finishes by contacting the support again is very unpractical.

I suppose the best option here is to turn it a third party extension, and add a "looking for contributors" notice on the README. Unfortunately maintaining the extension without having a commercial account in `travis.com` does not seem doable with the new changes.

**Comment by FlorianWilhelm** [comment]
To have less work I think it would also be a viable solution to just drop Travis support and wait until someone complains, then tell them that an external Travis extension under the PyScaffold organization is possible if there is also a maintainer volunteering.
