### ISSUE TITLE
No detailed error log during ErrorLoadingExtension

### ISSUE THREAD

**Issue by FlorianWilhelm** [pyscaffold/pyscaffold#378]
## Description of your problem

Just produce e.g. an import error in an extension. When running `putup --dsproject ...` the error will be:
```
ERROR: There was an error loading 'pyscaffoldext-dsproject'.
    Please make sure you have installed a version of the extension that is compatible
    with PyScaffold 4.0b3.post1.dev1+ge4a1a38. You can also try unininstalling it.
```

In order to get to the actual cause of the error `putup -vv --dsproject ...` should work but due to the fact that `ErrorLoadingExtension` is a `RuntimeError` and the fact that the plugins are loaded before the error level is set, thus
```
  if logger.level <= logging.DEBUG:
      # user surely wants to see the stacktrace
      traceback.print_exc()
  print(f"ERROR: {ex}")
```
in `exceptions2exit` does not work as intended.

To solve this one could replace the condition `logger.level <= logging.DEBUG` and do some partial parsing of `sys.argv` with https://docs.python.org/3/library/argparse.html#partial-parsing. 

## Versions and main components

* PyScaffold Version: current master
* Python Version: 3.8
* Operating system: MacOS
* How did you install PyScaffold: pip

**Comment by abravalheri** [comment]
Hi @FlorianWilhelm thank you for reporting this bug. It looks like a tricky one... I will try to have a look at it during the weekend (no promises :P).

Meanwhile, I think this might be solved by https://github.com/pyscaffold/pyscaffoldext-dsproject/pull/10 ...

**Comment by FlorianWilhelm** [comment]
This was fixed by @abravalheri. Thank you!
