### ISSUE TITLE
No overview in Sphinx docs

### ISSUE THREAD

**Issue by FlorianWilhelm** [pyscaffold/pyscaffold#379]
When checking out the `pyscaffoldext-markdown` extension I noticed that the Sphinx index is referencing the `README.md` as "overview", which I find pretty helpful. Checking out the Sphinx docs of the [demo-project](https://pyscaffold-demo.readthedocs.io/en/latest/) generated with vanilla PyScaffold, I noticed that there is no backlink to README.rst. Should this be added?

**Comment by abravalheri** [comment]
Hi @FlorianWilhelm, yes that definetely would be a nice improvement...

When changing the docs of the `pyscaffoldext-markdown` itself, I added a "Quickstart" (and later renamed to "Overview" following one of your commits) section inspired by the way I organised the `pyscaffoldext-{django,cookiecutter}`. Then when automating the procedure to the generated files, it got included. I find this trick very handy for small projects/docs.
