### ISSUE TITLE
To avoid crashes, we should release final versions of extensions first

### ISSUE THREAD

**Issue by abravalheri** [pyscaffold/pyscaffold#384]
... and then add their minimum versions to the `[all]` extra dependencies on `setup.cfg` before releasing te final v4.
Otherwise PyScaffold v4 might try to run with older versions of the extensions if they are already installed.

**Comment by FlorianWilhelm** [comment]
Totally agree!

**Comment by abravalheri** [comment]
Thank you very much @FlorianWilhelm, yesterday I went around making sure to have the latest PyScaffold beta for all the extensions. My idea was to release a version of them this week. Since most of them are pre-1.0, we don't really need a rc (in accordance with semantic versioning)

**Comment by abravalheri** [comment]
Hi @FlorianWilhelm, I pushed tags for almost all extensions (except dsproject because I wasn't sure if you wanted to do something else there), and updated PyScaffold's own `setup.cfg`  with minimum versions for the extensions.

I would say we are good to go for the pre-release, the only thing we might want to do is to release dsproject and update its min version as an extra dependency to PyScaffold...

**Comment by FlorianWilhelm** [comment]
Thanks, @abravalheri, I released `v0.5` of dsproject and changed it in `setup.cfg` of PyScaffold. This should be done.
