### ISSUE TITLE
tox -e build is using incorrect package version

### ISSUE THREAD

**Issue by EricWiener** [pyscaffold/pyscaffold#387]
## Description of your problem
When trying to build a package with `tox`, it is not updating the version number.

**Please provide a minimal, self-contained, and reproducible example.**

1. Commit all code
2. Tag code with version `git tag -a v0.0.1 -m "Initial version"`
3. Try to build with `tox -e build` and the resulting package will still have version `0.0.0`.

When I validate the version with `python setup.py --version`, I correctly get `0.0.1`. Additionally, if I do `python setup.py install` I will get the correctly versioned wheel.

**Please provide the full traceback.**
```bash
build installed: build==0.1.0,packaging==20.8,pep517==0.9.1,pyparsing==2.4.7,toml==0.10.2
build run-test-pre: PYTHONHASHSEED='4183370602'
build run-test: commands[0] | python -m build .
Collecting setuptools>=40.8.0
  Using cached setuptools-51.1.2-py3-none-any.whl (784 kB)
Collecting wheel
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel, setuptools
Successfully installed setuptools-51.1.2 wheel-0.36.2
WARNING: You are using pip version 20.3.1; however, version 20.3.3 is available.
You should consider upgrading via the '/Users/ericwiener/repositories/bbox-utils/.tox/build/bin/python -m pip install --upgrade pip' command.
/Users/ericwiener/anaconda3/envs/pyscaffold/lib/python3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'use_pyscaffold'
  warnings.warn(msg)
running sdist
running egg_info
writing src/bbox_utils.egg-info/PKG-INFO
writing dependency_links to src/bbox_utils.egg-info/dependency_links.txt
writing requirements to src/bbox_utils.egg-info/requires.txt
writing top-level names to src/bbox_utils.egg-info/top_level.txt
reading manifest file 'src/bbox_utils.egg-info/SOURCES.txt'
writing manifest file 'src/bbox_utils.egg-info/SOURCES.txt'
running check
creating bbox-utils-0.0.0
...
```

**Please provide any additional information below.**
[Here is the GitHub repo for the package
](https://github.com/EricWiener/bbox-utils)

## Versions and main components

* PyScaffold Version: 3.3
* Python Version: 3.9.1
* Operating system: mac OS
* How did you install PyScaffold: (conda/pip): conda

**Comment by EricWiener** [comment]
To add to this, when I try to install the package after publishing the version built with `python setup.py install`, I get the error:
```
ERROR: Requested bbox-utils==0.0.1 from https://files.pythonhosted.org/packages/ca/7b/4ae60a7599f50a3b57928f7c1905407aa3ff63e74a747b751c03a1669544/bbox_utils-0.0.1-py2.py3-none-any.whl#sha256=dd75ae18af871a7e1eb071385ad72bfcf07ddbb8ccffc6bb65d380270f6a05f6 has different version in metadata: '0.0.0'
```

It's very possible this is something I'm doing wrong (and not pyscaffold). I would really appreciate any advice

**Comment by EricWiener** [comment]
I looked at pyscaffold's `setup.py` and it is:
```
"""Setup file for PyScaffold."""
from setuptools import setup

if __name__ == "__main__":
    try:
        setup(use_scm_version={"version_scheme": "no-guess-dev"})
    except:  # noqa
        print(
            "\n\nAn error occurred while building the project, "
            "please ensure you have the most updated version of setuptools, "
            "setuptools_scm and wheel with:\n"
            "   pip install -U setuptools setuptools_scm wheel\n\n"
        )
        raise
```

while the default one created with putup for me is:
```
import sys
from pkg_resources import VersionConflict, require
from setuptools import setup

try:
    require("setuptools>=38.3")
except VersionConflict:
    print("Error: version of setuptools is too old (<38.3)!")
    sys.exit(1)


if __name__ == "__main__":
    setup(use_pyscaffold=True)
```

If I try to specify `use_scm_version` with:
```
setup(use_pyscaffold=True, use_scm_version={"version_scheme": "no-guess-dev"})
```

I get the error:
```
$ python setup.py --version
/Users/ericwiener/anaconda3/envs/pyscaffold/lib/python3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'use_scm_version'
  warnings.warn(msg)
```

**Comment by abravalheri** [comment]
Hi @EricWiener, thank you very much for bringing this issue forward.

Am I correct in assuming that you have copied a version of `tox.ini` from the master branch of PyScaffold repository to your project? If I am not wrong the `tox.ini` generated by `putup` in v3.3 should not include a `build` task... (if that is happening than we have a terrible bug :P -- please let me know so I can work in a patch).

Meanwhile you could try 2 things:

1. Update the project to v4 (I just pushed the release candidate version and that should be fairly stable -- we are in a phase of the project that we basically ready to release v4 and the RC is just for the users to have the chance to tell us any bugs or problems they might find)
    - If you do so, please remember to follow https://pyscaffold.org/en/latest/ instead of https://pyscaffold.org/en/stable
    - To update please commit all your current changes and try a `putup --update .`. If that is still not enough you can do a `putup --update --force .` and then use `git difftool` to check all overwritten files, especially `setup.cfg`, restoring things you might have overwriten.
2. Change `tox.ini` build task to not use the `build` package. I suppose you would have to do the following:
    - remove `build` from `deps` and add `PyScaffold==3.3` and `wheel` instead (maybe even a high enough version of `setuptools`)
    - use `python setup.py dists` instead of `python -m build .` in `cmd`
    - please notice other tasks on the master version of `tox.ini` might also not work in v3.3

**Comment by EricWiener** [comment]
@abravalheri thanks so much for the reply! You are correct that I copied a version of tox.ini from the master branch. I was following the docs and it mentioned using `tox -e build`, but that configuration didn't exist in my project, so I took it from master. I had thought it was something to do with me adding tox after I created the project vs. doing it in the initial putup step. 

What was most likely is that I was reading the docs for the latest branch and not the stable branch, so I ended up expecting 4.0 functionality on 3.3 code. I will attempt the first fix you suggested and hopefully, that works. Thank you!

**Comment by abravalheri** [comment]
Perfect @EricWiener, happy to see my answer makes sense. Please let me know if you have other problems.

To install v4, please rember to install PyScaffold using `pip install PyScaffold==4.0rc1` (I suspect a `pip install --pre` might also work).

**Comment by EricWiener** [comment]
@abravalheri was the travis extension removed from PyScaffold. I followed the latest docs:

>  and many more like --gitlab to create the necessary files for GitLab, --travis for TravisCI, or --cookiecutter for Cookiecutter integration.

But `putup bbox-utils --update --travis` throws:
```
usage: putup [-h] [-n NAME] [-p PACKAGE_NAME] [-d TEXT] [-l LICENSE] [-u URL] [-f] [-U] [-V] [-v] [-vv] [-P] [--list-actions] [--cirrus]
             [--config CONFIG_FILE [CONFIG_FILE ...] | --no-config] [--save-config [SAVE_CONFIG]] [--gitlab] [-i] [--namespace NS1[.NS2]] [--no-pyproject]
             [--no-skeleton] [--no-tox] [--pre-commit] [--venv [VENV]] [--venv-install PACKAGE [PACKAGE ...]]
             PROJECT_PATH
putup: error: unrecognized arguments: --travis
```

**Comment by EricWiener** [comment]
Besides the Travis question, the update went great! The new interactive config file was great and everything with tox worked out of the box. Thank you for all your work! If you wouldn't mind answering the Travis question, that would be awesome, but after that, I can close the issue

**Comment by abravalheri** [comment]
Hi @EricWiener, glad to hear things went better. Travis was moved to its own separated extension now, https://github.com/pyscaffold/pyscaffoldext-travis, maybe installing the extra package works? We should include this in the docs to make it more clear.

**Comment by abravalheri** [comment]
(We decided to move Travis because now they are changing their business model, and my feeling it is not going to be very practical to open source developers - it requires emailing their support team and asking for more open source credits everytime you run out of them... Cirrus CI is a nice alternative though)

**Comment by EricWiener** [comment]
Thanks so much! Using the extension worked perfectly (as did replacing `pip install -r requirements.txt` with `pip install tox-travis` in the `.travis.yml`). I really appreciate your help with this!

Also good to know about Cirrus CI. I think I'll plan on switching to them
