### ISSUE TITLE
Building external modules defined under [ext_modules] section does not work.

### ISSUE THREAD

**Issue by dsclassen** [pyscaffold/pyscaffold#388]
## Description of your problem

I am developing a python project that requires a custom module written in C. I would like to be able to build and install using

`pip install -e .`

I have added a section to my setup.cfg file. This is a just a guess because I could not find any examples of how to specify external modules in a pyscaffold project. I snooped around in the setup tools source code and I think this is what I need to define.

```
[ext_modules]
ext = [Extension("mymod", ["mymod.c"])]
```

**Please provide a minimal, self-contained, and reproducible example.**
```python
pip install -e .
```

**Please provide the full traceback.**

The pip install completes successfully, but never processes the `[ext_modules]` section.
I can put any keyword I want under the `[ext_modules]` section and I get no errors so it seems to be completely skipped.

**Please provide any additional information below.**

## Versions and main components

* PyScaffold Version: 3.3
* Python Version: 3.8.5
* Operating system: Mac OS Darwin Kernel Version 20.2.0
* How did you install PyScaffold: (conda/pip) pip

**Comment by abravalheri** [comment]
Hi @dsclassen, thank you very much for bringing this issue forward.

PyScaffold just configures setuptools in a project, so you can follow any documentation you find for setuptools. I am afraid that for the time being external modules have to be added directly to `setup.py`. All the keywords and sections supported by `setup.cfg` are documented here: https://setuptools.readthedocs.io/en/latest/userguide/declarative_config.html?highlight=setup.cfg. The good thing is that you can leave all the other configurations in `setup.cfg` and just deal with the C extensions in `setup.py`.

This part of setuptools is not very well documented, but I can see that you can do `from setuptools.extension import Extension`, and the remainder of the `setup.py` file should be fairly similar to https://docs.python.org/3/extending/building.html.

**Comment by dsclassen** [comment]
Great! Thanks for the quick response and the confirmation of what I suspected. I'll proceed with configuring external C modules in `setup.py` for now.
