### ISSUE TITLE
Mention in the extensions docs the usage of ${qual_pkg} instead of ${package}

### ISSUE THREAD

**Issue by abravalheri** [pyscaffold/pyscaffold#391]
It is very easy when creating new extensions to forget to consider namespaces, therefore we should mention this in the extension docs.

Replacing the usages of `${package}` with `${qual_pkg}` should work for the vast majority of the cases.

References:
https://github.com/pyscaffold/pyscaffoldext-dsproject/issues/11
https://github.com/pyscaffold/pyscaffoldext-custom-extension/issues/24

**Comment by FlorianWilhelm** [comment]
Thanks a lot @abravalheri!
