### ISSUE TITLE
exclude doesn't exclude folders

### ISSUE THREAD

**Issue by Diyago** [pyscaffold/pyscaffold#404]
## Description of your problem

**Please provide a minimal, self-contained, and reproducible example.**
I would like to exclude tests, images and Research folder from the list, but they anyway included to it. Full code here https://github.com/Diyago/GAN-for-tabular-data
_setup.cfg_
```
[options.packages.find]
where = src
exclude =
    tests
    Research
    images
```

**Please provide the full traceback.**
```python
no error
```

**Please provide any additional information below.**

## Versions and main components

* PyScaffold Version: 3.3
* Python Version: 3.8
* Operating system: Mac os
* How did you install PyScaffold: (conda/pip) pip

**Comment by FlorianWilhelm** [comment]
Hi @Diyago, I just cloned your repo and ran:

> ❯ python setup.py bdist_wheel
running bdist_wheel
running build
running build_py
running egg_info
writing src/tabgan.egg-info/PKG-INFO
writing dependency_links to src/tabgan.egg-info/dependency_links.txt
writing requirements to src/tabgan.egg-info/requires.txt
writing top-level names to src/tabgan.egg-info/top_level.txt
writing manifest file 'src/tabgan.egg-info/SOURCES.txt'
installing to build/bdist.macosx-10.9-x86_64/wheel
running install
running install_lib
creating build/bdist.macosx-10.9-x86_64/wheel
creating build/bdist.macosx-10.9-x86_64/wheel/_ctgan
copying build/lib/_ctgan/models.py -> build/bdist.macosx-10.9-x86_64/wheel/_ctgan
copying build/lib/_ctgan/__init__.py -> build/bdist.macosx-10.9-x86_64/wheel/_ctgan
copying build/lib/_ctgan/README.MD -> build/bdist.macosx-10.9-x86_64/wheel/_ctgan
copying build/lib/_ctgan/transformer.py -> build/bdist.macosx-10.9-x86_64/wheel/_ctgan
copying build/lib/_ctgan/synthesizer.py -> build/bdist.macosx-10.9-x86_64/wheel/_ctgan
copying build/lib/_ctgan/conditional.py -> build/bdist.macosx-10.9-x86_64/wheel/_ctgan
copying build/lib/_ctgan/sampler.py -> build/bdist.macosx-10.9-x86_64/wheel/_ctgan
creating build/bdist.macosx-10.9-x86_64/wheel/tabgan
copying build/lib/tabgan/abc_sampler.py -> build/bdist.macosx-10.9-x86_64/wheel/tabgan
copying build/lib/tabgan/__init__.py -> build/bdist.macosx-10.9-x86_64/wheel/tabgan
copying build/lib/tabgan/encoders.py -> build/bdist.macosx-10.9-x86_64/wheel/tabgan
copying build/lib/tabgan/adversarial_model.py -> build/bdist.macosx-10.9-x86_64/wheel/tabgan
copying build/lib/tabgan/utils.py -> build/bdist.macosx-10.9-x86_64/wheel/tabgan
copying build/lib/tabgan/sampler.py -> build/bdist.macosx-10.9-x86_64/wheel/tabgan
running install_egg_info
Copying src/tabgan.egg-info to build/bdist.macosx-10.9-x86_64/wheel/tabgan-0.1.9.post0.dev1+gd9a0fde-py3.8.egg-info
running install_scripts
adding license file "LICENSE" (matched pattern "LICEN[CS]E*")
adding license file "AUTHORS.rst" (matched pattern "AUTHORS*")
creating build/bdist.macosx-10.9-x86_64/wheel/tabgan-0.1.9.post0.dev1+gd9a0fde.dist-info/WHEEL
creating 'dist/tabgan-0.1.9.post0.dev1+gd9a0fde-py2.py3-none-any.whl' and adding 'build/bdist.macosx-10.9-x86_64/wheel' to it
adding '_ctgan/README.MD'
adding '_ctgan/__init__.py'
adding '_ctgan/conditional.py'
adding '_ctgan/models.py'
adding '_ctgan/sampler.py'
adding '_ctgan/synthesizer.py'
adding '_ctgan/transformer.py'
adding 'tabgan/__init__.py'
adding 'tabgan/abc_sampler.py'
adding 'tabgan/adversarial_model.py'
adding 'tabgan/encoders.py'
adding 'tabgan/sampler.py'
adding 'tabgan/utils.py'
adding 'tabgan-0.1.9.post0.dev1+gd9a0fde.dist-info/AUTHORS.rst'
adding 'tabgan-0.1.9.post0.dev1+gd9a0fde.dist-info/LICENSE'
adding 'tabgan-0.1.9.post0.dev1+gd9a0fde.dist-info/METADATA'
adding 'tabgan-0.1.9.post0.dev1+gd9a0fde.dist-info/WHEEL'
adding 'tabgan-0.1.9.post0.dev1+gd9a0fde.dist-info/top_level.txt'
adding 'tabgan-0.1.9.post0.dev1+gd9a0fde.dist-info/RECORD'
removing build/bdist.macosx-10.9-x86_64/wheel

As you can see only the files under `src` are added as expected. Or what do you mean by tests, images, and Research folder are included anyway? Included into what?

**Comment by Diyago** [comment]
I would like to exclude tests, images, and Research folders from distributive, but they added anyway:
<img width="502" alt="image" src="https://user-images.githubusercontent.com/8073766/108272187-f7157d80-7182-11eb-94d6-1bc6e2d990c0.png">

**Comment by FlorianWilhelm** [comment]
The problem is the `sdist` format, which ignores a lot of the configurations in `setup.cfg`. You can create a new file `MANIFEST.in` with content:
```
prune tests
prune Research
prune images
```

I would recommend though to use the new wheel format by running `python setup.py bdist_wheel` to create distributions.

**Comment by Diyago** [comment]
wow thank you a lot, didn't know about `bdist_wheel`. By the way in the instructions said to use `sdist` , not info about bdist_wheel

**Comment by FlorianWilhelm** [comment]
It's already updated in the [documentation of version 4](https://pyscaffold.org/en/latest/features.html) which will be released soon.

**Comment by sgbaird** [comment]
I'm trying to figure out why GitHub actions is [including more than just the `src` folder](https://github.com/sparks-baird/self-driving-lab-demo/actions/runs/3679664930/jobs/6224375040) and causing a `File too large.` error [when trying to publish to PyPI](https://github.com/sparks-baird/self-driving-lab-demo/actions/runs/3679664930/jobs/6224475214).
