### ISSUE TITLE
Conda-forge build failing

### ISSUE THREAD

**Issue by maresb** [pyscaffold/pyscaffold#413]
See https://github.com/conda-forge/pyscaffold-feedstock/pull/27

It looks to me like between v3.3 and v4.0, `configupdater` was moved from `.contrib` to an external dependency, but there is not yet a `configupdater` feedstock.

**Comment by FlorianWilhelm** [comment]
@maresb, thanks for posting this issue, this is correct. Would you be interested in contributing by helping to generate feedstocks for PyScaffolds dependencies and maybe also the extensions?

**Comment by maresb** [comment]
I'm interested, but I've never generated feedstocks before. I suppose I could give [this](https://conda-forge.org/docs/maintainer/adding_pkgs.html) a try, but I'd appreciate help if I get stuck.

**Comment by FlorianWilhelm** [comment]
Thanks a lot, @maresb! Maybe it's also a good idea to contact @ocefpaf since he wrote the initial feedstock for PyScaffold as far as I know.

**Comment by maresb** [comment]
> GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.

@FlorianWilhelm Could I list you as a maintainer?

If so, please post to my PR https://github.com/conda-forge/staged-recipes/pull/14169

**Comment by maresb** [comment]
Fixed!

**Comment by FlorianWilhelm** [comment]
That's really great @maresb, thank you for your contribution!

**Comment by maresb** [comment]
There were some tests missing on the original pyscaffold feedstock. I added them back in, and now there's this failure:
```
+ pip check
pyscaffold 4.0 has requirement configupdater<2,>=1.1.3, but you have configupdater 2.0.
```
This is blocking for generating other packages like pyscaffoldext-dsproject.

I only built configupdater 2.0, and it's way too much effort to make a special 1.1.3 build.

Conda-forge builds from PyPI, so we have to wait for #410 to land in a release before this can be fixed.

**Comment by maresb** [comment]
Feedstock PR in progress here: https://github.com/conda-forge/pyscaffold-feedstock/pull/28

**Comment by maresb** [comment]
Hmm, I just noticed that 4.0.1rc1 is on PyPI. Let's see if that works...

**Comment by FlorianWilhelm** [comment]
@maresb Yes, you are right, PyScaffold 4.0 depends on configupdater < 1.1.3 since all release candidates were tested with it. The easiest thing would be to wait for PyScaffold 4.0.1 that will depend on configupdater >=2.0,<3.0. I guess PyScaffold 4.0.1 will be released in a few weeks depending on the feedback. CC @abravalheri

**Comment by abravalheri** [comment]
Sorry @maresb, I released it yesterday according to a previous plan I had with Florian... I hope it is not problematic

**Comment by maresb** [comment]
I properly fixed this issue, unfortunately at the cost of [publishing rc1 to the main conda-forge index](https://github.com/conda-forge/pyscaffold-feedstock/issues/29).
