### ISSUE TITLE
Improve information about conda in docs

### ISSUE THREAD

**Issue by abravalheri** [pyscaffold/pyscaffold#427]
Currently we have [this information available about conda](https://pyscaffold.org/en/latest/conda.html).
According to @maresb review on #424:

> A potential problem I see is that "Creating Conda Packages" is a very niche topic which 99% of users will probably never do. But using conda in conjunction with PyScaffold in particular dsproject is a very important mainstream theme. This niche topic is now very prominent in the PyScaffold documentation, while (as far as I can tell) there isn't really a prominent explanation of using conda in general. I think this gives the wrong impression about what conda is mainly for. I wonder if it would be better to:
> 
> - rename the topic "Creating Conda Packages" → "Using Conda Packages",
> - describe using conda as a package manager, the environment.yml file, etc, and
> - put this section which you just wrote at the end.

Those are really great suggestions that would be nice to adopt.

Hopefully we can borrow some of the previous writings from @FlorianWilhelm on #368 and #426 to compose the extra sections.

Additionally this section should be at least linked to [Dependency Management](https://pyscaffold.org/en/latest/dependencies.html) (should we keep them 2 separated sections or put conda under the Dependency Management? but then talking about how to create conda packages seem a bit weird... not sure how to organise everything in a cohesive way).

**Comment by FlorianWilhelm** [comment]
I'll look into that. I like the idea of putting it into the dependency management section and describe how to use conda instead of creating an own conda package. I'll work on a proposal PR.

**Comment by abravalheri** [comment]
Thank you very much @FlorianWilhelm

**Comment by FlorianWilhelm** [comment]
This was fixed in #446.
