### ISSUE TITLE
Tox not installing extras in default setup

### ISSUE THREAD

**Issue by tdamsma** [pyscaffold/pyscaffold#438]
I noticed tox was failoing due to pytest extensions not installed, and on further inspection it seems the `extras = testing` in tox is ignored, or at least whatever I put in the testing section in my setup.cfg is never installed by tox.

To reproduce: 
    - create a new project on (in my case python 3.9) with `putup ttt`
    - add any package to setup.cfg testing, e.g.

    --- a/setup.cfg
    +++ b/setup.cfg
    @@ -64,6 +64,7 @@ testing =
        setuptools
        pytest
        pytest-cov
    +    pytest-black
 
Output from `tox -v` reveals it does try to install the testing env:

    ttt$ /ttt/.tox/default/bin/python -m pip install --no-deps -U '/ttt/.tox/.tmp/package/1/ttt-0.0.0.zip[testing]' >.tox/default/log/default-18.log

However `pytest-black` is not installed. I changed the test command to `pip freeze` and it never shows:

    default run-test: commands[0] | pip freeze
    attrs==20.3.0
    coverage==5.5
    iniconfig==1.1.1
    packaging==20.9
    pluggy==0.13.1
    py==1.10.0
    pyparsing==2.4.7
    pytest==6.2.3
    pytest-cov==2.11.1
    toml==0.10.2
    ttt @ file:///ttt/.tox/.tmp/package/1/ttt-0.0.0.zip

**Comment by abravalheri** [comment]
Hi @tdamsma, have you tried to run `tox -r` after changing `setup.cfg`? I usually have the impression that `tox` does not detect changes automatically on `setup.cfg`.

**Comment by tdamsma** [comment]
Thanks for the quick reply @abravalheri, that indeed does the trick!

**Comment by abravalheri** [comment]
Good news!

@tdamsma I think the next step here would open an issue directly on `tox` directly. In terms of PyScaffold there is very little we could do. What are your thoughts about that?

**Comment by tdamsma** [comment]
Will be solved in tox 4

**Comment by FlorianWilhelm** [comment]
Thanks @tdamsma, for clarifying this :-) and thanks @abravalheri for being a tox guru ;-)
