### ISSUE TITLE
Read The Docs seems to not find correct version

### ISSUE THREAD

**Issue by abravalheri** [pyscaffold/pyscaffold#454]
The new theme uses the `version` config to render a top bar on smaller screens.

Unfortunately, it seems that when building on RTD, `version` ends up being equal to `unknown`, as indicated in the image bellow. So I suspect it might be an issue with the `setuptools-scm` integration.

![missing version](https://user-images.githubusercontent.com/320755/120916583-594aad80-c6a2-11eb-827b-fc1ec62888d2.png)

After looking at the [build logs](https://readthedocs.org/api/v2/build/13938623.txt), I tried to replicated the issue with the following steps:

```bash
$ mkdir -p /tmp/pyscaffold
$ cd /tmp/pyscaffold
$ git clone --no-single-branch --depth 50 https://github.com/pyscaffold/pyscaffold .
$ git checkout --force origin/master
$ virtualenv -p py38 .venv
$ .venv/bin/python -m pip install --upgrade --no-cache-dir pip setuptools
$ .venv/bin/python -m pip install --exists-action=w --no-cache-dir -r docs/requirements.txt
$ cd docs
$ ../.venv/bin/python
```
```python
>>> import sys
>>> sys.path.insert(0, '../src')
>>> from pyscaffold import __version__ as version
>>> version
'unknown'
```

The version is `unknown` even if I run the commands from the root of the project (instead of from inside the docs folder). Apparently the package needs to be installed (e.g. with `pip install -e .`) for `setuptools-scm` to work.

This is the recommendation from `setuptools-scm`:

[![setuptools-scm](https://user-images.githubusercontent.com/320755/120917928-b4cc6980-c6a9-11eb-9df0-bae798ace60a.png)](https://github.com/pypa/setuptools_scm#usage-from-sphinx)

However, without the editable install, it also fails
```python
>>> import sys
>>> sys.path.insert(0, '../src')
>>> from pyscaffold import __version__ as version
>>> version
'unknown'
>>> from importlib.metadata import version
>>> release = version('pyscaffold')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/importlib/metadata.py", line 472, in version
    return distribution(distribution_name).version
  File "/usr/lib/python3.8/importlib/metadata.py", line 445, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 169, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: pyscaffold
```

Alternatively I tried:
```python
>>> from setuptools_scm import get_version
>>> get_version(root='..', relative_to='conf.py')
/tmp/pyscaffold/.venv/lib/python3.8/site-packages/setuptools_scm/git.py:88: UserWarning: "/tmp/pyscaffold" is shallow and may cause errors
  warnings.warn(f'"{wd.path}" is shallow and may cause errors')
'4.0.3.dev7+g192f609'
```

However this does not considers the `setuptools-scm` configurations in either `pyproject.toml`, or `setup.py`.

**Comment by FlorianWilhelm** [comment]
Might it be that the clone depth is not high unknown?

**Comment by FlorianWilhelm** [comment]
'unknown' is set in __init__.py if anything goes wrong. What is the actual error that leads to this?

**Comment by abravalheri** [comment]
Hi @FlorianWilhelm,

When I clone locally with the same depth used by RTD, the depth is enough to show the latest minor tag at least, and if I run the `get_version(root='..', relative_to='conf.py')`, it does get it right.

> unknown is set in __init__.py if anything goes wrong. What is the actual error that leads to this?

So no error is actually being raised, exactly because of this `try/except` in the `__init__.py` file, if I comment the `try/except`, I get a `PackageNotFoundError` from `importlib.metadata` (similar error with `pkg_resources`).

I think this happens because RTD does not install the project, we get it by manipulating `sys.path`.

I am currently working on a PR for this that uses an env var provided by RTD... Not sure it is the best way around, but it removes the `unknown`:

![rtd](https://user-images.githubusercontent.com/320755/120920447-bfd9c680-c6b6-11eb-896a-3534ddc80042.png)

**Comment by FlorianWilhelm** [comment]
@abravalheri, couldn't this bug maybe be easily fixed by letting RTD just install the package? In this case `from pyscaffold import __version__` just works. One could do this by adding `-e .` at the bottom of `docs/requirements.txt`. I just tried this and it seems to work on my machine. 

Thanks a log for the reproduction steps, I did:
```
$ mkdir -p /tmp/pyscaffold
$ cd /tmp/pyscaffold
$ git clone --no-single-branch --depth 50 https://github.com/pyscaffold/pyscaffold .
$ git checkout --force origin/master
$ virtualenv -p py38 .venv
$ .venv/bin/python -m pip install --upgrade --no-cache-dir pip setuptools
# at this point I added `-e .` at the bottom of docs/requirements.txt
$ .venv/bin/python -m pip install --exists-action=w --no-cache-dir -r docs/requirements.txt
$ cd docs
$ ../.venv/bin/python
```
Then I ran:
```
>>> from pyscaffold import __version__ as version
>>> version
```
and it showed the correct version.

**Comment by abravalheri** [comment]
That is actually a clever idea.

Since it would is redundant for `tox -e docs`, what do you think about adding this to the RTD config instead? [According to the docs](https://docs.readthedocs.io/en/stable/config-file/v2.html#python) it could be done with:

```yaml
python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt
    - {method: pip, path: .}
```

**Comment by FlorianWilhelm** [comment]
Cool, thanks, looks good to me.
