### ISSUE TITLE
Should we also move the generated projects doc template from Alabaster to Furo?

### ISSUE THREAD

**Issue by abravalheri** [pyscaffold/pyscaffold#472]
I was thinking about that... While Alasbaster is very minimal and great when you want to right plain text (e.g. a blog post) it feels very grey without any configuration for project documentations (of course, with some customisation it can look very sharp and smart, like we see in [nox](https://nox.thea.codes/en/stable/index.html)). 

Furo on the other hand can be very color/cheerful out of the box, while still being minimal.

There are also many other options: https://sphinx-themes.org

**Comment by FlorianWilhelm** [comment]
I actually like the simplicity of Alabaster especially for small projects and it can be changed later quite easily. Also, it comes with Sphinx directly and you don't need to install it additionally. For that reason, I would rather stick with Alabaster.

**Comment by abravalheri** [comment]
Thanks Florian
