### ISSUE TITLE
Should we add a PyScaffold Badge to the generated README's?

### ISSUE THREAD

**Issue by abravalheri** [pyscaffold/pyscaffold#473]
This is a follow up on #469.

We currently have a footer saying "Project generated with PyScaffold", maybe we should also add a badge on top of the page? People love visual stimulation, and badges are cool.

**Comment by FlorianWilhelm** [comment]
Thanks, @abravalheri, let's close this issue when we have it also in the markdown and dsproject extension. I'll take a shot at it if I find some time over the weekend.

**Comment by FlorianWilhelm** [comment]
As this is also done now in `pyscaffoldext-dsproject` and `pyscaffoldext-markdown`, we can close this issue.

**Comment by abravalheri** [comment]
Thanks @FlorianWilhelm
