### ISSUE TITLE
LookupError: setuptools-scm was unable to detect version for 'c:\\my\\project'

### ISSUE THREAD

**Issue by bravegag** [pyscaffold/pyscaffold#486]
We have the following versions:
```
Python==3.7.3 (or 3.7.4)
PyScaffold==3.2.3
setuptools==50.3.0
pip==21.2.4
```

We have been working with multiple PyScaffold-generated projects in Windows 7 no problem. I was able to always pip install, build the `bdist_wheel` etc. no problem. We're very happy with PyScaffold btw, vgj! After migrating to Windows 10 our projects stopped working, we can no longer run the following commands successfully:
```
pip install -e .
python setup.py bdist_wheel
```

We get the following error:
```
(env) c:\my\project>pip install -e .
Looking in indexes: https://some.nexus.some.where/repository/public-lib-python-pypi/simple
Obtaining file:///C:/my/project
    ERROR: Command errored out with exit status 1:
     command: 'c:\my\env\scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'c:\\my\\project\\setup.py'"'"'; __file__='"'"'c:\\my\\project\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\xxx\AppData\Local\Temp\2\pip-pip-egg-info-io_7dpde'
         cwd: c:\my\project\
    Complete output (29 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File " c:\my\project\setup.py", line 23, in <module>
        setup(use_pyscaffold=True)
      File "c:\my\env\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\my\miniconda3\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "c:\my\env\lib\site-packages\setuptools\dist.py", line 424, in __init__
        k: v for k, v in attrs.items()
      File "C:\my\miniconda3\lib\distutils\dist.py", line 292, in __init__
        self.finalize_options()
      File "c:\my\env\lib\site-packages\setuptools\dist.py", line 695, in finalize_options
        ep(self)
      File "c:\my\env\lib\site-packages\setuptools\dist.py", line 702, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "c:\my\env\lib\site-packages\pyscaffold\integration.py", line 105, in pyscaffold_keyword
        version_keyword(dist, keyword, setuptools_scm_config(value))
      File "c:\my\env\lib\site-packages\pyscaffold\contrib\setuptools_scm\integration.py", line 17, in version_keyword
        dist.metadata.version = get_version(**value)
      File "c:\my\env\lib\site-packages\pyscaffold\contrib\setuptools_scm\__init__.py", line 150, in get_version
        parsed_version = _do_parse(config)
      File "c:\my\env\lib\site-packages\pyscaffold\contrib\setuptools_scm\__init__.py", line 113, in _do_parse
        "use git+https://github.com/user/proj.git#egg=proj" % config.absolute_root
    LookupError: setuptools-scm was unable to detect version for 'C:\\my\\project'.

    Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work. 

    For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
    ----------------------------------------
WARNING: Discarding file:///C:/my/project. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Could this be to a setting in Windows 10 or could it be due to Git failing to provide metadata? The `.git` is at the expected level `C:/my/project` and all git commands work correctly e.g. git tag --list etc.

**Comment by FlorianWilhelm** [comment]
Hi @bravegag, this looks like an error in an old version of `setuptools-scm`. In PyScaffold 3.X, we used to vendorize (meaning we bundled) setuptools-scm for several reasons. With PyScaffold 4.x a newer version of `setuptools-scm` is used. Could you upgrade your project to PyScaffold 4.0.2? My best guess is that Windows 10 comes with newer git versions and thus the old `setuptools-scm` version fails.

**Comment by bravegag** [comment]
@FlorianWilhelm thanks a lot! this is very helpful. It is a good lead. Is there an automated way to upgrade a PyScaffold generated project from 3.x to 4.x? We have a dozen of projects generated and would be great to have it somehow automated ...

**Comment by bravegag** [comment]
@FlorianWilhelm I did what you suggested and followed the migration 3.x -> 4.x instructions here https://pyscaffold.org/en/v4.0/updating.html.

I now get a different error coming from setuptools_scm: `OSError: 'git' was not found`

The relevant package versions are now the following:
```
python==3.7.3
PyScaffold==4.0.2
setuptools==57.4.0
setuptools_scm==6.0.1
wheel==0.37.0
```

I have git installed under `C:\Program Files\Git\` I do the following from a `setupenv.bat`:

    set PATH="C:\Program Files\Git\bin";%PATH%

So doing the following I can see it:

    echo %PATH%

The following will then work:

    git --version
    >git version 2.21.0.windows.1

But this won't:

    where git
    >INFO: Could not find files for the given pattern(s)

**Comment by bravegag** [comment]
Thanks a lot, it now works. For git to be found by the `where` command and `setuptools-scm` the set PATH must in Windows 10 be without double quotes. Like this will work for the PyScaffold 3 and 4. The problem on 3 was a poor error message whereas in 4 was revealing the git not found issue.

**Comment by FlorianWilhelm** [comment]
Thanks for taking the time and posting the resolution of the problem :-) If you want you can also make a PR for our [FAQ](https://pyscaffold.org/en/stable/faq.html). We always welcome information about Windows, as neither @abravalheri nor I use it as a development platform.
