### ISSUE TITLE
Should we remove the [bdist_wheel] section from setup.cfg template?

### ISSUE THREAD

**Issue by abravalheri** [pyscaffold/pyscaffold#497]
Both [packaging guides](https://packaging.python.org/guides/distributing-packages-using-setuptools/#wheels) and [wheels docs](https://wheel.readthedocs.io/en/stable/quickstart.html) seems to suggest that the following section makes sense if the project supports Python 2 and Python 3 at the same time.
```ini
[bdist_wheel]
universal = 1
```

I suppose we don't need this anymore in the template, since it is no longer a "best practice", right?

My understanding is that by default the wheel made is a pure Python3 one, which should work in every system.
(PyScaffold's own `setup.cfg` doesn't have it and things seem to be working fine).

**Comment by FlorianWilhelm** [comment]
At the time I was adding this, I thought that it rather tells `wheel` that the package contains no compiled extensions and thus it's *universal* with respect to the platform. Maybe this changed over time and now `wheel` infers this itself. Long story short. Yes, I think we should just remove it from the template then. Directly in version 4.1 as it is only a minor change?

**Comment by abravalheri** [comment]
I think we can add it to 4.1, release a rc3 asap and then release the final version first half of next week 😝 
I am excited for 4.1!

**Comment by FlorianWilhelm** [comment]
I am also extremely excited about it! and I love the new RTD theme :-)

**Comment by FlorianWilhelm** [comment]
Let's also release a new version of `pyscaffoldext-markdown` and `pyscaffoldext-dsproject` a couple of weeks or so after 4.1. This gives us some time to see if something comes up and test the extensions with the new version.

**Comment by abravalheri** [comment]
Perfect, let me create a temporary workaround for pyscaffold/pyscaffoldext-markdown#25.
