### ISSUE TITLE
Removing Description headline from default template

### ISSUE THREAD

**Issue by FlorianWilhelm** [pyscaffold/pyscaffold#498]
## Describe your use-case

I noticed that in the default README template:
```
# ${name}

${description}

## Description

A longer description of your project goes here...
```
I tend to remove `## Description` and rather have it as a new paragraph directly under `${description}`. Is it only me or could this be a reasonable change that improves our template?

## Describe the solution you would like to see for your use-case

Remove `## Description` and have `A longer description of your project goes here...` in a new paragraph directly under `${description}`.

**Comment by abravalheri** [comment]
How about doing that but emphasizing the short `${description}` as if it was an abstract (e.g. [pyscaffoldext-cookiecutter](https://github.com/pyscaffold/pyscaffoldext-cookiecutter))?
