### ISSUE TITLE
Fix https for pyscaffold.org

### ISSUE THREAD

**Issue by FlorianWilhelm** [pyscaffold/pyscaffold#546]
## Description of your problem

Something is off with the RTD, Cloudflare, Strato setup as we have only HTTP which is strange and lowers our Google ranking.

![image](https://user-images.githubusercontent.com/3184072/144273080-cebb2247-1992-47ce-a1dd-5d8558943625.png)

**Comment by abravalheri** [comment]
Ouch, this one seems to be a tricky one...

**Comment by FlorianWilhelm** [comment]
Cool, actually it was only setting two checks in RTD. Done :-)

**Comment by abravalheri** [comment]
Thank you very much @FlorianWilhelm!
