### ISSUE TITLE
Missing flag in the publish-package GitHub workflow

### ISSUE THREAD

**Issue by git-afsantos** [pyscaffold/pyscaffold#551]
## Description of your problem

As per the discussion in https://github.com/pyscaffold/pyscaffold/discussions/550:

> The last step of the `publish-package.yml` workflow runs the following commands to build and publish the package to PyPI.
> 
> ```shell
> python -m pip install --upgrade pip setuptools tox
> python -m tox -e clean,build
> python -m tox publish -- --verbose --repository pypi
> ```
> 
> The [last line](https://github.com/pyscaffold/pyscaffold/blob/de7aa5dc059fbd04307419c667cc4961bc9df4b8/.github/workflows/publish-package.yml#L33) in particular, seems to be missing the `-e` option. Without it, `tox` would run the default environment, which, in this case, runs `pytest`.
> 
> It seems however that tox managed to guess and do the right thing (I can see the latest releases were uploaded to PyPI). But this behaviour is undocumented and should not be relied upon...

## Versions and main components

* PyScaffold Version: v4.1.1
* Python Version: any
* Operating system: any
* How did you install PyScaffold: pip

**Comment by git-afsantos** [comment]
I will submit a PR to fix this issue shortly.

**Comment by abravalheri** [comment]
Thank you very much for the help André!
