### ISSUE TITLE
Add some more debugging information about called functions for `--very-verbose`-mode.

### ISSUE THREAD

**Issue by FlorianWilhelm** [pyscaffold/pyscaffold#562]
In issue #556 we have seen that `--very-verbose`-mode can be hard to interpret sometimes. For instance there are several
```
         run      git.exe rev-parse --git-dir
    last command failed with "fatal: not a git repository (or any of the parent directories): .git"
```
in the output. Only by looking in the code one finds out that this is done in the `is_git_repo` function. So we could add debug statements to functions like `is_git_repo` but the question is where? Two alternatives:

1. Within `is_git_repo` like "Checking if {cwd} is git repository" or
2. rather outside where we could even state our intention like "Making sure that parent directory {dir} is no git repo".

Alternative 1. is more straightforward, less code and even less error-prone as you cannot forget to add a debug statement when another `is_git_repo` call is introduced. Alternative 2. provides more information about the intention, which is only available outside, and could thus be more informative when looking for errors.

Not sure what the best practice is but a few more debug statements could help. The goal should be that the output of `putup --very-verbose my_test_proj` is easy to interpret at least for us developers.

**Comment by abravalheri** [comment]
Oops, sorry for creating a release before we had the chance to consider this issue 😅 

I did a quick search and apparently `is_git_repo` is only called in 2 places 

`actions.verify_project_dir`
https://github.com/pyscaffold/pyscaffold/blob/0dbaf83f35bbd9546dc5174f01f89b33338bebed/src/pyscaffold/actions.py#L303

and  `actions.init_git`
https://github.com/pyscaffold/pyscaffold/blob/0dbaf83f35bbd9546dc5174f01f89b33338bebed/src/pyscaffold/actions.py#L320

So going for option 2 is still viable... Would it make sense to pass a `log` argument with a custom message to the `is_git_repo` function? If none is given we can fallback to the generic/non-informative message...

**Comment by FlorianWilhelm** [comment]
No problem, I already thought that this could go in the next release.

If you also like alternative 2 I would take a look and prep a PR. It will not only be `is_git_repo` but also other functions like it. Basically all functions that execute shell commands.

**Comment by abravalheri** [comment]
Thank you @FlorianWilhelm

**Comment by FlorianWilhelm** [comment]
Resolved in the PR above.
