### ISSUE TITLE
setuptools-scm seems to break unit tests

### ISSUE THREAD

**Issue by FlorianWilhelm** [pyscaffold/pyscaffold#563]
Our [unittests break ](https://cirrus-ci.com/task/4762004492648448) in `test_sdist_install_dirty` and `test_sdist_install_with_1_0_tag_dirty`. Strangely those tests fail only under `test (OS X)` and `coverage (Linux - 3.6)`.

This is the stacktrace.
```python
AssertionError: assert (False or False)
  +  where False = <built-in method endswith of str object at 0x103224300>('.d20220109')
  +    where <built-in method endswith of str object at 0x103224300> = 'ge9df8ac.d20220110'.endswith
  +  and   False = <built-in method endswith of str object at 0x103224440>('.d2022010')
  +    where <built-in method endswith of str object at 0x103224440> = 'ge9df8ac.d2022011'.endswith
```
The stacktrace shows that somehow the new automatic generated version string is the date like `d20220109`. This is quite strange as we use `no-guess-dev` for setuptools-scm's configuration. Strange is that the current setuptools-scm version is `6.3.2` from September 21th, 2021. So why does this appear now?

## Versions and main components

* PyScaffold Version: master
* Python Version: *
* Operating system: Mac/Linux
* How did you install PyScaffold: (conda/pip)

**Comment by abravalheri** [comment]
Hi @FlorianWilhelm, thank you for bringing this up.

So what is happening is that the dates as wrong by one day off?

**Comment by FlorianWilhelm** [comment]
Ah right, the dirty tag suffix is `.d2022...`. So the question is what is in the `local` variable at that point? Maybe it's missing the dirty tag at all? That the day is wrong day off should be fine as it ran in the morning and maybe this was still yesterday in the US.

**Comment by FlorianWilhelm** [comment]
@abravalheri, suddenly it works again 😕 . Let's close this.

**Comment by abravalheri** [comment]
> what is in the `local` variable at that point? Maybe it's missing the dirty tag at all?

The value for local in the broken test was `ge9df8ac.d20220110`, so the dirty tag seems to be present.
[At some point](https://github.com/pyscaffold/pyscaffold/commit/06637aa34bc9dac2d1168aab6c2d484d36bc072d) I introduced a little trick to avoid failing on one of those *off-by-one* errors but [that hack](https://github.com/pyscaffold/pyscaffold/blob/abcbdbbbbf6932489fa7146db06c3558889155fe/tests/test_install.py#L196) is not good enough. I would have worked if the test suite was running on the 11th 😝
