### ISSUE TITLE
Conda packages get no longer updated

### ISSUE THREAD

**Issue by FlorianWilhelm** [pyscaffold/pyscaffold#570]
## Description of your problem

There are no new packages on conda-forge for versions `4.1.2` and `4.1.3`. We should fix this.

The problem seems to be that we don't publish source distributions anymore to pypi. For instance, looking under
[version 4.1.1 files](https://pypi.org/project/PyScaffold/4.1.1/#files) there is a `tar.gz` but not under [version 4.1.2 files](https://pypi.org/project/PyScaffold/4.1.2/#files) and [version 4.1.2 files](https://pypi.org/project/PyScaffold/4.1.3/#files) anymore. I couldn't find a change in our build configuration from 4.1.1 that explains this. So no idea :-( 

Those files are needed in [meta.yml](https://github.com/conda-forge/pyscaffold-feedstock/blob/master/recipe/meta.yaml).

**Comment by abravalheri** [comment]
That is the link: https://github.com/pyscaffold/pyscaffold/pull/535#discussion_r739685295

**Comment by abravalheri** [comment]
I am also inclined to remove the following phrases from the docs:

```rst
Source distributions, i.e. sdist, are only recommended if you absolutely need them.
They are tricky to configure and may ignore several options in setup.cfg.
```

I believe that the problems with `sdist` x `wheel` in setuptools at this point is considered solved, right? (Reference: https://github.com/abravalheri/experiment-setuptools-package-data#results-for-setuptools5920)

**Comment by FlorianWilhelm** [comment]
Cool that this is solved! Thanks. Then let's have it back in the docs.
