### ISSUE TITLE
Note to our future selves: it seems that the community is moving past `appdirs` and that a more maintained fork has appeard: `platformdirs`.

### ISSUE THREAD

**Issue by abravalheri** [pyscaffold/pyscaffold#581]
It seems that the community is moving past `appdirs` and that a more maintained fork has appeared: `platformdirs`.

Ref:
- https://github.com/ActiveState/appdirs/issues/79
- https://github.com/ActiveState/appdirs/issues/170

So for the next version we might consider replacing the dependency (which should be API compatible).

_Originally posted by @abravalheri in https://github.com/pyscaffold/pyscaffold/issues/580#issuecomment-1025542512_

**Comment by julie777** [comment]
I have actually been doing quite a bit of research into XDG directories and on the python solutions to make it easy for applications and tools to find and use the correct directories.

In addition to platformdirs and appdirs there is also [pyxdg](https://freedesktop.org/wiki/Software/pyxdg/). There are probably more packages out there that do the same thing. So far I know that virtualenv uses platformdirs and pyscaffold uses appdirs.

I have some opinionated thoughts on the matter based on my recent cross platform work, which includes trying to develop on windows using all the bash on Windows variants, such as cygwin, msys, git-bash, etc.

1. I think that all platforms should use the XDG environment variables if they are defined. This is the only way to give real control to the user about where files end up. I'm sure some Windows people will have a different opinion, but with the advent of WSL the Windows and Linux world are merging for developers.
2. I think it would be great if an effort was made to converge on a single package that supports directory location functionality. I would even like to see it become part of the standard library. It really is hard to develop for multi-platform use and get everything right.

I am not trying to disagree, but rather just add a little more to the discussion.

**Comment by abravalheri** [comment]
Hi @julie777, thank you very much for the insights!

Regarding your opinion on (1), I agree with that, if the `XDG_*` vars are defined it is reasonable to suppose the users want to place files in an specific place... Have you considered raising this issue in `platformdirs`? I think before we implement it in PyScaffold, that should be targeted "upstream".

Regarding (2), specifically speaking in terms of the Python community, my opinion is that `platformdirs` is the strongest candidate, if any package was to be accepted as part of the stdlib...

This however is a long and turbulent path that involve a lot of discussion and a formal PEP proposal. I also don't know how the steering committee would react to that, last time I checked the impression I had is that they want to "remove the dead batteries" first before adding new ones. It might be worthy to bring up the topic in the [Python discourse](https://discuss.python.org).

**Comment by julie777** [comment]
I have submitted an issue to platformdirs. I am also going to talk to freedesktop.org about clarifying some of the missing or ambiguous parts of the XDG spec.
