### ISSUE TITLE
Broken links in the documentation

### ISSUE THREAD

**Issue by abravalheri** [pyscaffold/pyscaffold#585]
According to the [CI](https://cirrus-ci.com/task/4735827958824960), the following links are broken:

- https://docs.pytest.org/en/stable/usage.html#dropping-to-pdb-python-debugger-at-the-start-of-a-test ([this link](https://docs.pytest.org/en/stable/how-to/failures.html#using-python-library-pdb-with-pytest) seems to be a suitable replacement)

**Comment by FlorianWilhelm** [comment]
Thanks @abravalheri!
