### ISSUE TITLE
Improve docs to help users make sure they install `pre-commit`

### ISSUE THREAD

**Issue by julie777** [pyscaffold/pyscaffold#607]
## Description of your problem

I checked in files with blank lines at the end. When I pushed they were changed to remove the blank line. This left me in the state that my github pyscaffold repo was ahead of my local repo.

All commit hooks should be part of the repo and be able to run locally before pushing code.

**Please provide any additional information below.**

## Versions and main components

* PyScaffold Version: 4.1.4
* Python Version: 3.10.2
* Operating system: Windows/git-bash
* How did you install PyScaffold: pipx

**Comment by julie777** [comment]
I could use a pointer to information about the .pre-commit-config.yaml. It isn't something I am familiar with.

**Comment by julie777** [comment]
I just found out that I missed a step setting my environment so pre-commit is installed.
Now that I have installed it I am trying to understand why it produces an error when I try to run it

**Comment by julie777** [comment]
You can close this. After tracking down a bug in pre-commit and hacking it to work for me, everything is fine.

**Comment by julie777** [comment]
I think that I will submit a doc change later to help make it easier for future developers.

**Comment by julie777** [comment]
I really need to go back and carefully read all the documentation. 
While getting started and getting to know the project I was jumping around so much that I probably missed some important information.

Is there a reason that `pre-commit` is separated out from the dependency installation `pip install -U pip setuptools -e .`?

Honestly, I just missed that step. I ran `pip install...` and expected everything to be ready to go.

**Comment by FlorianWilhelm** [comment]
I think it's separated out from `pip install -U pip setuptools -e .` to make clear that two steps are needed for the `pre-commit` setup. Also for each step, a small explanation is given on why we do it.

Can this issue be closed, or what change to the docs should be done?

**Comment by abravalheri** [comment]
Ok, I think I will close this issue for now, because there are some instructions in place already. But if anyone wants to improve the docs, please feel free to file a PR!
