### ISSUE TITLE
Support "0.1.0" instead of only "v0.1.0" (not preprending `v` causes issues with GitHub actions and PyPI publishing)

### ISSUE THREAD

**Issue by sgbaird** [pyscaffold/pyscaffold#639]
From what I understand, having the v prepended is [historical and optional](https://stackoverflow.com/a/28605963/13697228) for semantic versioning 2.0. It's a simple fix to support both in GitHub actions:
```
tags: ['v*', '*.*.*', '*.*']
```

But I'm not really sure what I would need to change for the PyPI package uploading. It seems to be mainly an issue of getting `pip install -e .` to recognize the tag.

```bash
(xtal2png) PS C:\Users\sterg\Documents\GitHub\sparks-baird\xtal2png> git tag --delete "v0.1.0"
Deleted tag 'v0.1.0' (was 9ea8951)
(xtal2png) PS C:\Users\sterg\Documents\GitHub\sparks-baird\xtal2png> pip install -e .
Obtaining file:///C:/Users/sterg/Documents/GitHub/sparks-baird/xtal2png
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: pillow in c:\users\sterg\miniconda3\envs\xtal2png\lib\site-packages (from xtal2png==0.1.0.post1.dev4+g151df9d) (9.0.1)
... <removed for brevity>
Installing collected packages: xtal2png
  Attempting uninstall: xtal2png
    Found existing installation: xtal2png 0.1.0
    Uninstalling xtal2png-0.1.0:
      Successfully uninstalled xtal2png-0.1.0
  Running setup.py develop for xtal2png
Successfully installed xtal2png-0.1.0.post1.dev4+g151df9d
(xtal2png) PS C:\Users\sterg\Documents\GitHub\sparks-baird\xtal2png> git tag "v0.1.0"         
(xtal2png) PS C:\Users\sterg\Documents\GitHub\sparks-baird\xtal2png> pip install -e .
Obtaining file:///C:/Users/sterg/Documents/GitHub/sparks-baird/xtal2png
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: pymatgen in c:\users\sterg\miniconda3\envs\xtal2png\lib\site-packages (from xtal2png==0.1.0) (2022.5.19)
... <removed for brevity>
Installing collected packages: xtal2png
  Attempting uninstall: xtal2png
    Found existing installation: xtal2png 0.1.0.post1.dev4+g151df9d
    Uninstalling xtal2png-0.1.0.post1.dev4+g151df9d:        
      Successfully uninstalled xtal2png-0.1.0.post1.dev4+g151df9d
  Running setup.py develop for xtal2png
Successfully installed xtal2png-0.1.0
```

Thinking I might just switch back to the common / historical `v*.*.*` convention - just have gotten used to `*.*.*` tags across quite a few repositories, but maybe not a big deal since I'm probably not going to convert those to PyScaffold projects - just trying out PyScaffold for repos going forward. In other words, not a huge deal for me, especially if it would be a pain to implement. Happy to PR any changes as well if this seems like something worth supporting.

Digging a little bit further, I'm seeing this line in `setup.py`:
```python
setup(use_scm_version={"version_scheme": "no-guess-dev"})
```

and came across the following which seems pretty relevant: https://github.com/pypa/setuptools_scm#setuptools_scm.

**Comment by sgbaird** [comment]
xref: https://github.com/pyscaffold/pyscaffold/issues/267

**Comment by abravalheri** [comment]
Thank you very much @sgbaird.
I don't have a very strong preference either to be sincere...

What do you think about the following change?
```yaml
tags: ['v[0-9]*', '[0-9]+.[0-9]+*']
```

This should avoid some accidental matches, right?

(I am considering that we want to support things like `2013.10`, `v1.3rc1`, `0.42b1`, etc...)
