### ISSUE TITLE
tox stopped working on GitHub actions due to tox major version update

### ISSUE THREAD

**Issue by sgbaird** [pyscaffold/pyscaffold#683]
## Description of your problem

My GitHub actions CI suddenly started giving the following error https://github.com/sparks-baird/self-driving-lab-demo/actions/runs/3666140871/jobs/6197685437#step:5:18:
```python
tox -e py --installpkg dist/*.whl
```
```python
ROOT: HandledError| .pkg_external is already defined as a virtualenv-cmd-builder, cannot be virtualenv-pep-517 too
Error: Process completed with exit code 254.
```

At one point, it was also installing Python 3.11 even though ["3.10" was specified](https://github.com/sparks-baird/self-driving-lab-demo/blob/c01c507e0d7710e51366d4338befcd10910c2ce3/.github/workflows/ci.yml#L35). Seemed to be fixed by moving the with argument to a new line

Mentioned by someone else here https://github.com/beeware/briefcase/pull/994.

I haven't repro'd this from scratch with the latest build yet.

**Please provide any additional information below.**
Scheduled test on **2022-12-07T14:06:55.6352295Z** that ran successfully: https://github.com/sparks-baird/self-driving-lab-demo/actions/runs/3639637826
Scheduled test on **2022-12-07T22:07:25.2284089Z** that failed: https://github.com/sparks-baird/self-driving-lab-demo/actions/runs/3643224057
Note that it's the same commit (i.e. no difference between the repos)

## Versions and main components

> This project has been set up using [PyScaffold] 4.2.3.post1.dev10+g7a0f254 and the [dsproject extension] 0.7.2.post1.dev3+g948a662.

**Comment by sgbaird** [comment]
Here's the diff between the raw logs of the two scheduled tests: https://www.diffchecker.com/cY0t8GlT
![image](https://user-images.githubusercontent.com/45469701/206883092-1f721238-6c1e-496d-9e9e-f3ca184bbb1e.png)

The only differences, except for the error message and what follows, that I found were timestamps and a temporary directory location.

**Comment by sgbaird** [comment]
I verified that GitHub Actions tests fail on a fresh installation of PyScaffold (`v4.3.1`) and tox (`v4.0.6`) https://github.com/sparks-baird/tox-debug/actions/runs/3667288545

**Comment by abravalheri** [comment]
Hi @sgbaird I believe you already found out this is related to https://github.com/tox-dev/tox/issues/2442.

Probably an unintended backward incompatible change in tox?

I donknow if it is worthy to pin `tox` to an earlier version... The problem with that would be that tox v3 is no longer actively maintained.

**Comment by sgbaird** [comment]
Hi @abravalheri, thanks for the quick response! Right now, I'm struggling to figure out how to even pin `tox` to an earlier version as part of the debugging process and as a short-term workaround. Also, I think it will work with `tox==v4.0.0rc4` (if not, then probably `v4.0.0rc3`) since it's prior to Dec 7, but I want to verify. Do you know how `tox` can be pinned in `ci.yml`?

**Comment by sgbaird** [comment]
Ok, as a temporary workaround, I figured out how to pin tox version https://github.com/sparks-baird/tox-debug/actions/runs/3667510986. Replace all instances of
```python
pipx run tox
```
with e.g.
```python
pipx run --spec tox==3.27.1 tox
```

**Comment by abravalheri** [comment]
Thank you very much @sgbaird.

I updated the templates and tested them against the newest versions of `tox`. I believe they should be working now.
