### ISSUE TITLE
Tests don't run with the correct Python version in GitHub Actions

### ISSUE THREAD

**Issue by koenvervloesem** [pyscaffold/pyscaffold#686]
## Description of your problem
My expectation was that the "Run tests" step of the test job were run with the Python version set up in the `setup-python` action of the same job. So when `${{ matrix.python }}` is 3.7, I would expect that the tests on all three operating systems would run on Python 3.7.

Instead, I see the tests running on different versions depending on the operating system in `${{ matrix.platform }}`:

* `ubuntu-latest`: Python 3.10
* `macos-latest`: Python 3.11
* `windows-latest`: Python 3.9

**Please provide any additional information below.**

You can see this in action in [this action run of my project humble-explorer](https://github.com/koenvervloesem/humble-explorer/actions/runs/3768030025), that I bootstrapped last month with PyScaffold.

* In the [test run for Ubuntu](https://github.com/koenvervloesem/humble-explorer/actions/runs/3768030025/jobs/6406134266) `pytest` starts with `platform linux -- Python 3.10.6, pytest-7.2.0, pluggy-1.0.0 -- /home/runner/work/humble-explorer/humble-explorer/.tox/default/bin/python`.
* In the [test run for macOS](https://github.com/koenvervloesem/humble-explorer/actions/runs/3768030025/jobs/6406134330) `pytest` starts with `platform darwin -- Python 3.11.0, pytest-7.2.0, pluggy-1.0.0 -- /Users/runner/work/humble-explorer/humble-explorer/.tox/default/bin/python`. 
* In the [test run for Windows](https://github.com/koenvervloesem/humble-explorer/actions/runs/3768030025/jobs/6406134386) `pytest` starts with `platform win32 -- Python 3.9.13, pytest-7.2.0, pluggy-1.0.0 -- D:\a\humble-explorer\humble-explorer\.tox\default\Scripts\python.EXE`.

I just noticed this because my project used some version-specific Python features and didn't fail in the right test runs. The test runs seem to use the default system-wide installed versions of Python on these GitHub action runners instead of the ones set up by the `setup-python` action.

## Possible solution

I solved this in my case by adding `id: setup-python` to the `setup-python` step so I could refer to the path of the installed Python interpreter, and then adding the parameter `--python '${{ steps.setup-python.outputs.python-path }}'` after `pipx run` when running the tests, to explicitly set the Python binary to use. See [this commit](https://github.com/koenvervloesem/humble-explorer/commit/1753674acbc369bef3685ead07e268c83f7c829f) for an example.

This seems to do the job: with this change the [action runs the tests on Python 3.7 ](https://github.com/koenvervloesem/humble-explorer/actions/runs/3776652661) when `${{ matrix.python }}` is 3.7, on all operating systems. I checked this too for 3.8, 3.9, 3.10 and 3.11.

If you agree with this solution, I can create a PR to fix this in PyScaffold's GitHub CI template.

## Versions and main components

* PyScaffold Version: 4.3.1
* Python Version: 3.10.6
* Operating system: Ubuntu 22.04.1 LTS
* How did you install PyScaffold: pip

**Comment by abravalheri** [comment]
Hi @koenvervloesem thank you very much for reporting this problem.

In #693 (specifically 3e287c26ba767d4087f45e2f544b04c1dd3dbcc3), I am using the suggested approach but only for `pipx run tox`.
It seems that this is only affecting the tox invocation (the coverage seems to be fine for example)
I also tried a different approach by setting the `PIPX_DEFAULT_PYTHON` env var, but that did not work...

Please, let me know if you have any other concern that the change did not address.

**Comment by koenvervloesem** [comment]
That looks great!
