### ISSUE TITLE
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. pyscaffold 4.4.1 requires platformdirs<3,>=2, but you have platformdirs 3.5.0 which is incompatible.

### ISSUE THREAD

**Issue by alexcoca** [pyscaffold/pyscaffold#719]
## Description of your problem

PyScaffold uses outdated `platformdirs`

1. Install pyscaffold
```bash
pip install --upgrade pyscaffold
```

2. Install `tox`
 ```bash
pip install tox
```

**Please provide the full traceback using the `--very-verbose` flag.**
```python
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyscaffold 4.4.1 requires platformdirs<3,>=2, but you have platformdirs 3.5.0 which is incompatible
```

This occurs because `tox` requires `platformdirs>3.2`.

## Versions and main components

* PyScaffold Version: 4.4.1
* Python Version: 3.9.6
* Operating system: MacOS
* How did you install PyScaffold: pip

**Comment by m1guelperez** [comment]
Yes same. Would be nice if they upgrade the dependency version
