### ISSUE TITLE
https://pyscaffold.org's DNS is misconfigured

### ISSUE THREAD

**Issue by webknjaz** [pyscaffold/pyscaffold#750]
This is causing problems with the link checkers, besides being inaccessible: https://github.com/pypa/packaging.python.org/actions/runs/9750566682/job/26910254850?pr=1569

**Comment by webknjaz** [comment]
For anybody landing on this page from google, the last archived snapshot of the website is available at https://web.archive.org/web/20240502194201/https://pyscaffold.org/en/stable/.

**Comment by webknjaz** [comment]
Aha.. So it's backed by RTD! And there was a successful build today even: https://app.readthedocs.org/projects/pyscaffold/builds/?version__slug=&state=succeeded&version__type=.

**Comment by webknjaz** [comment]
I know that CloudFlare doesn't like it when a domain for a website hosted on RTD is put in DNS proxy mode. That's probably what's happened.

**Comment by webknjaz** [comment]
Yep, that's it! The A-records point to CloudFlare CDN:
```console
$ dig @1.1.1.1 www.pyscaffold.org a    

; <<>> DiG 9.16.42 <<>> @1.1.1.1 www.pyscaffold.org a
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 53004
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;www.pyscaffold.org.		IN	A

;; ANSWER SECTION:
www.pyscaffold.org.	234	IN	A	188.114.96.9
www.pyscaffold.org.	234	IN	A	188.114.97.9

;; Query time: 6 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Tue Jul 02 00:42:36 CEST 2024
;; MSG SIZE  rcvd: 79


$ dig @1.1.1.1 pyscaffold.org a    

; <<>> DiG 9.16.42 <<>> @1.1.1.1 pyscaffold.org a
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 50181
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;pyscaffold.org.			IN	A

;; ANSWER SECTION:
pyscaffold.org.		226	IN	A	188.114.97.9
pyscaffold.org.		226	IN	A	188.114.96.9

;; Query time: 13 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Tue Jul 02 00:42:40 CEST 2024
;; MSG SIZE  rcvd: 75


$ dig -x 188.114.97.9

; <<>> DiG 9.16.42 <<>> -x 188.114.97.9
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 61268
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;9.97.114.188.in-addr.arpa.	IN	PTR

;; AUTHORITY SECTION:
97.114.188.in-addr.arpa. 629	IN	SOA	darl.ns.cloudflare.com. dns.cloudflare.com. 2288625646 10000 2400 604800 3600

;; Query time: 13 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Jul 02 00:42:45 CEST 2024
;; MSG SIZE  rcvd: 116
```

**Comment by webknjaz** [comment]
@abravalheri @FlorianWilhelm I assume one of you has access to CF? The fix is to click on that cloud icon next to the `@` and `www` A-records and this should get back to normal.

**Comment by sgbaird** [comment]
Any update here? Still seeing:

![image](https://github.com/user-attachments/assets/0e1c415d-ad5a-47b4-8cbf-5c11becccd7b)

**Comment by Haleshot** [comment]
> For anybody landing on this page from google, the last archived snapshot of the website is available at https://web.archive.org/web/20240502194201/https://pyscaffold.org/en/stable/.

Thanks! This is helpful! Hope the maintainers can take a look at the PR you raised and resolve it.

**Comment by webknjaz** [comment]
Apparently, it's working again.
