### ISSUE TITLE
src cause ModuleNotFoundError

### ISSUE THREAD

**Issue by vipcxj** [pyscaffold/pyscaffold#753]
## Description of your problem
By default pyscaffold create a src dir and put all code under it. I think it cause many problem. At lease vscode launch can not find the package because it does not know the package is under src but root project directory.

**Please provide a minimal, self-contained, and reproducible example.**
```python
# [Your code here]
```

**Please provide the full traceback using the `--very-verbose` flag.**
```python
# [The error output here]
```

**Please provide any additional information below.**

## Versions and main components

* PyScaffold Version:
* Python Version:
* Operating system:
* How did you install PyScaffold: (conda/pip)

**Comment by abravalheri** [comment]
Hi @vipcxj, thank you for your comment.

I believe that you probably have to install the project first, for example using the editable mode: `pip install -e .`.

It seems that vscode also have some settings that you may be able to use (e.g. `autoSearchPaths`: https://code.visualstudio.com/docs/python/settings-reference).

The src-layout is a very popular layout in the Python community and also recommended in the [PyPUG tutorial](https://packaging.python.org/en/latest/tutorials/packaging-projects/), so in principle there is nothing wrong with that.
